-- The site's copy: every published string, in every locale. GENERATED FILE -- do not hand-edit.
--
-- Written by scripts/generate-prose-seed.mjs from the published rows in the hosted database.
-- To refresh it after staff publish a copy change worth keeping in the restore point:
--
--     node --env-file=.env.local scripts/generate-prose-seed.mjs
--
-- ---------------------------------------------------------------------------------------
-- WHY THIS IS SEED DATA AND NOT A MIGRATION (#126)
-- ---------------------------------------------------------------------------------------
--
-- Five migrations insert prose, and every one is scoped `where o.slug = 'willow-grove'`. On a
-- fresh `supabase db reset` the migrations run BEFORE seed.sql, so `public.orgs` is empty, the
-- cross join matches nothing, and all five insert nothing. A database rebuilt from the
-- repository had no copy at all -- and since the site reads 293 of its 296 strings from this
-- table, that is not a degraded site, it is a build that fails.
--
-- A later migration cannot repair the earlier ones: migrations run in filename order, so a new
-- one lands after them and would have to carry the whole catalogue itself, putting the copy in
-- two places. It is data. It belongs here.
--
-- The five migrations stay as they are. They ran correctly against the hosted project, which is
-- the only database that existed when they were written, and rewriting applied migrations to
-- tidy up history is a worse habit than leaving them as no-ops on a rebuild.
--
-- ---------------------------------------------------------------------------------------
-- PROVENANCE
-- ---------------------------------------------------------------------------------------
--
--     rows 586 (de 293, en 293), md5 933fd056176c84d974f044fbfd9fac8a
--
-- The digest covers the sorted (locale, namespace, key, value) tuples. Re-run the generator; if
-- the digest matches, this file still says what the database says. #76 established the practice
-- and the reason: nobody verifies 586 strings by eye, and everybody reports that they did.
--
-- ---------------------------------------------------------------------------------------
-- RE-RUNNABLE, AND IT PRESERVES DRAFTS
-- ---------------------------------------------------------------------------------------
--
-- `on conflict (cols) where status = 'published'` names the published partial index explicitly.
-- #93 is why the predicate is spelled out: `on conflict (cols)` alone cannot choose between the
-- table's two partial indexes and Postgres refuses to plan the statement at all.
--
-- It also means re-seeding conflicts against published rows only, so a staff member's
-- unpublished draft survives untouched -- the same property every statement in seed.sql has.

insert into public.prose (org_id, locale, namespace, key, value, status)
select o.id, v.locale, v.namespace, v.key, v.value, 'published'
from public.orgs o
cross join (values
  ('de', 'AboutPage', 'eyebrow', 'Lizenziert seit {since}'),
  ('de', 'AboutPage', 'heading', 'Wie wir Kinder betreuen, und warum'),
  ('de', 'AboutPage', 'intro', 'Eine Einrichtung lässt sich leicht gut beschreiben und schwer gut führen. Diese Seite ist das Zweite — wie die Gruppen besetzt sind, was die Lizenz hinter der Eingangstür tatsächlich abdeckt und was an den gewöhnlichen Tagen passiert, über die niemand eine Broschüre schreibt.'),
  ('de', 'AboutPage', 'licensingBody', 'Wir haben seit {since} ununterbrochen eine staatliche Betriebserlaubnis für Kinderbetreuung. Eine Lizenz ist keine Urkunde an der Wand, sondern ein Prüfverfahren — und uns ist lieber, Sie wissen genau, was sie abdeckt, bevor Sie fragen.'),
  ('de', 'AboutPage', 'licensingCoversBuilding', 'Gebäude, Außengelände, Fluchtwege und Übungen'),
  ('de', 'AboutPage', 'licensingCoversHeading', 'Was eine Prüfung abdeckt'),
  ('de', 'AboutPage', 'licensingCoversKitchen', 'Küche, Umgang mit Lebensmitteln und Allergiepraxis'),
  ('de', 'AboutPage', 'licensingCoversRatios', 'Betreuungsschlüssel und Aufsicht, Gruppe für Gruppe'),
  ('de', 'AboutPage', 'licensingCoversRecords', 'Personalakten, Nachweise und Fortbildungsunterlagen'),
  ('de', 'AboutPage', 'licensingCoversSleep', 'Sicherer Schlaf, Liegen und Schlafroutinen'),
  ('de', 'AboutPage', 'licensingHeading', 'Lizenz und die Kontrollen dahinter'),
  ('de', 'AboutPage', 'licensingInspectionsLabel', 'Prüfungen'),
  ('de', 'AboutPage', 'licensingInspectionsValue', 'Unangekündigt, mindestens jährlich'),
  ('de', 'AboutPage', 'licensingNumberLabel', 'Staatliche Lizenz'),
  ('de', 'AboutPage', 'licensingRecords', 'Die Behörde führt unsere vollständige Prüfhistorie, und Sie haben das Recht, sie einzusehen. Fragen Sie im Büro, und wir zeigen Ihnen unsere, samt Beanstandungen.'),
  ('de', 'AboutPage', 'licensingSinceLabel', 'Lizenziert seit'),
  ('de', 'AboutPage', 'licensingStaffLine', 'Von jeder Mitarbeiterin und jedem Mitarbeiter liegt vor dem ersten Tag mit Kindern ein Führungszeugnis vor, und alle haben aktuelle Nachweise in Erster Hilfe und Reanimation — die Leitung eingeschlossen.'),
  ('de', 'AboutPage', 'metaDescription', 'Eine lizenzierte Kindertagesstätte in Northwest Portland seit {since} — unser Ansatz, unsere Betreuungsschlüssel, unsere staatliche Lizenz und wie Sicherheit an einem gewöhnlichen Tag aussieht.'),
  ('de', 'AboutPage', 'metaTitle', 'Über uns'),
  ('de', 'AboutPage', 'philosophyHeading', 'Woran wir glauben'),
  ('de', 'AboutPage', 'philosophyKnownBody', 'Jedes Kind hat eine feste Bezugsperson, und die Fachkräfte bleiben das Jahr über bei ihrer Gruppe. Deshalb können wir Ihnen beim Abholen sagen, dass Ihr Sohn sein Mittagessen halb aufgegessen hat und dann auf dem Lesekissen eingeschlafen ist — jemand war die ganze Zeit dabei.'),
  ('de', 'AboutPage', 'philosophyKnownTitle', 'Ein Kind sollte von wenigen gekannt werden, nicht von vielen beaufsichtigt'),
  ('de', 'AboutPage', 'philosophyPlainBody', 'Wenn Ihr Kind jemanden gebissen hat, sagen wir es Ihnen. Wenn eine Gruppe voll ist und die Wartezeit neun Monate beträgt, sagen wir neun Monate, statt Sie hoffen zu lassen. Man kann sein Kind nicht dort lassen, wo man Ausweichen erlebt hat.'),
  ('de', 'AboutPage', 'philosophyPlainTitle', 'Eltern bekommen die Wahrheit, auch die unangenehmen Teile'),
  ('de', 'AboutPage', 'philosophyRhythmBody', 'Jeden Tag derselbe Rhythmus — ankommen, frühstücken, Morgenkreis, raus, Mittagessen, ausruhen. Ein Kind, das weiß, was als Nächstes kommt, hat den Mut, darin erfinderisch zu sein. Erst die Struktur macht das Chaos möglich.'),
  ('de', 'AboutPage', 'philosophyRhythmTitle', 'Der Tag sollte vorhersehbar sein, das Spiel nicht'),
  ('de', 'AboutPage', 'ratiosAges', 'Alter'),
  ('de', 'AboutPage', 'ratiosBody', 'Das sind die Zahlen, mit denen wir jede Stunde besetzen, die wir geöffnet haben, kein Durchschnitt über die Woche. Beides zählt: Der Schlüssel bestimmt, wie viel Aufmerksamkeit Ihr Kind bekommt, die Gruppengröße, wie laut und wie voll es um es herum ist.'),
  ('de', 'AboutPage', 'ratiosFootnote', 'Unsere Schlüssel liegen auf oder unter dem, was die Behörde für jedes Alter verlangt, und wir halten sie über Mittagsschlaf, Mittagessen und das Ende des Tages — die Stunden, in denen ein Schlüssel am leichtesten still nachgibt.'),
  ('de', 'AboutPage', 'ratiosGroup', 'Gruppengröße'),
  ('de', 'AboutPage', 'ratiosHeading', 'Betreuungsschlüssel und Gruppengrößen'),
  ('de', 'AboutPage', 'ratiosRatio', 'Schlüssel'),
  ('de', 'AboutPage', 'ratiosRoom', 'Gruppe'),
  ('de', 'AboutPage', 'ratiosTableCaption', 'Betreuungsschlüssel und Gruppengröße nach Gruppe'),
  ('de', 'AboutPage', 'safetyAllergyBody', 'Allergien hängen im Gruppenraum und in der Küche aus, die Mahlzeiten entstehen im Haus, sodass wir bestimmen, was darin ist, und Medikamente werden nur nach Ihrer schriftlichen Anweisung gegeben und dabei dokumentiert.'),
  ('de', 'AboutPage', 'safetyAllergyTitle', 'Allergien und Medikamente'),
  ('de', 'AboutPage', 'safetyBody', 'Sicherheit ist meistens nicht dramatisch. Sie besteht aus denselben kleinen Abläufen, jeden Tag gleich ausgeführt, von Menschen, die nicht improvisieren.'),
  ('de', 'AboutPage', 'safetyDrillsBody', 'Brandschutzübungen monatlich und Notfallabläufe vierteljährlich, mit den Kindern, damit ihnen der Ablauf vertraut statt beängstigend ist.'),
  ('de', 'AboutPage', 'safetyDrillsTitle', 'Geübt, nicht nur geplant'),
  ('de', 'AboutPage', 'safetyEntryBody', 'Ein einziger Eingang mit Zahlencode, der jedes Halbjahr gewechselt wird. Niemand, der nicht auf der Abholliste Ihres Kindes steht, geht mit ihm hinaus — keine Ausnahmen an der Tür, nie, so plausibel die Person auch wirkt.'),
  ('de', 'AboutPage', 'safetyEntryTitle', 'Eine verschlossene Tür'),
  ('de', 'AboutPage', 'safetyHeading', 'Sicherheit an einem gewöhnlichen Tag'),
  ('de', 'AboutPage', 'safetyIllnessBody', 'Fieber, Erbrechen oder etwas Ansteckendes heißt nach Hause und vierundzwanzig Stunden beschwerdefrei zu Hause bleiben. Das ist unpraktisch, und es ist der Grund, warum nicht nächste Woche die ganze Gruppe krank ist.'),
  ('de', 'AboutPage', 'safetyIllnessTitle', 'Krankheit, klar gesagt'),
  ('de', 'AboutPage', 'safetySignInBody', 'Jedes Kind wird namentlich an- und abgemeldet, und die Fachkräfte zählen ihre Gruppe bei jedem Wechsel — in den Raum hinein, hinaus auf den Hof, vom Hof zurück.'),
  ('de', 'AboutPage', 'safetySignInTitle', 'Angemeldet und gezählt'),
  ('de', 'AboutPage', 'visitAria', 'Besuch planen'),
  ('de', 'AboutPage', 'visitBody', 'Nichts davon ist auf einem Bildschirm viel wert. Jede Einrichtung wirkt zur Schlafenszeit ruhig; was Sie sehen wollen, ist ein Raum mit wachen Kindern darin, und das geht nur, wenn Sie darin stehen.'),
  ('de', 'AboutPage', 'visitHeading', 'Worauf es ankommt, erlebt man im Raum'),
  ('de', 'Center', 'ageRange', '6 Wochen bis 5 Jahre'),
  ('de', 'Center', 'hoursCompact', '7–18 Uhr'),
  ('de', 'Center', 'hoursShort', 'Mo–Fr, 7:00–18:00 Uhr'),
  ('de', 'Center', 'neighborhood', 'Northwest Portland, einen Block vom Wallace Park'),
  ('de', 'ContactPage', 'callBody', 'Eine Nummer erreicht alles. Wenn Sie gleich sagen, worum es geht, kommen Sie schneller zur richtigen Person.'),
  ('de', 'ContactPage', 'callHeading', 'Weswegen anrufen, und wen Sie bekommen'),
  ('de', 'ContactPage', 'callHoursBody', 'Nach achtzehn Uhr läuft der Anrufbeantworter, abgehört wird er, wenn das Büro am nächsten Morgen um sieben öffnet. Über Nacht wird nichts beantwortet; was bis dahin nicht warten kann, sollte also keine Nachricht sein.'),
  ('de', 'ContactPage', 'callHoursTitle', 'Außerhalb der Öffnungszeiten'),
  ('de', 'ContactPage', 'callIllnessBody', 'Rufen Sie vor neun an, damit die Gruppe ihren Morgen planen kann. Nennen Sie das Symptom, nicht die Diagnose; ob es ein Ausschluss für vierundzwanzig Stunden ist, herauszufinden ist unsere Aufgabe, nicht Ihre.'),
  ('de', 'ContactPage', 'callIllnessTitle', 'Ihr Kind ist heute krank'),
  ('de', 'ContactPage', 'callPlaceBody', 'Fragen Sie nach Nadia, die die Warteliste führt. Sie sagt Ihnen, welche Gruppen Platz haben, und wenn die gewünschte keinen hat, wie lang die Wartezeit ehrlich ist — auch dann, wenn die Antwort fast ein Jahr lautet.'),
  ('de', 'ContactPage', 'callPlaceTitle', 'Ein Platz für Ihr Kind'),
  ('de', 'ContactPage', 'drivingBody', 'Vier markierte Plätze neben dem Gebäude sind zum Bringen und Abholen reserviert, jeweils fünfzehn Minuten. Das Parken auf der Straße ist im Block unbeschränkt, und am hinteren Ende ist selbst um halb neun meist etwas frei.'),
  ('de', 'ContactPage', 'drivingTitle', 'Auto und Parken'),
  ('de', 'ContactPage', 'emailNote', 'E-Mails werden einmal am Tag gelesen, nachmittags. Wenn es um einen Platz, ein Startdatum oder ein krankes Kind geht, rufen Sie bitte an — Sie bekommen die Antwort im selben Gespräch statt morgen.'),
  ('de', 'ContactPage', 'eyebrow', 'Eine Nummer, eine Adresse'),
  ('de', 'ContactPage', 'factAddressLabel', 'Adresse'),
  ('de', 'ContactPage', 'factClosedLabel', 'Geschlossen'),
  ('de', 'ContactPage', 'factClosedValue', 'Wochenenden und gesetzliche Feiertage'),
  ('de', 'ContactPage', 'factEmailLabel', 'E-Mail'),
  ('de', 'ContactPage', 'factHoursLabel', 'Geöffnet'),
  ('de', 'ContactPage', 'footBody', 'Einen Block vom Wallace Park entfernt, mit überdachtem Fahrradständer hinter dem Tor. Kinderwagen und Buggys kommen in den Eingangsflur statt in die Gruppenräume — dort ist Platz dafür, und die Türen bleiben frei.'),
  ('de', 'ContactPage', 'footTitle', 'Zu Fuß und mit dem Rad'),
  ('de', 'ContactPage', 'gettingHereBody', 'Wir liegen in einer Wohnstraße, was um acht Uhr morgens schön ist und lästig, wenn Sie auf Parkplatzsuche kreisen. Hier steht, wie die Bringzeit wirklich aussieht, damit Ihr erstes Abgeben nicht auch Ihr erstes Herausfinden ist.'),
  ('de', 'ContactPage', 'gettingHereHeading', 'Herkommen'),
  ('de', 'ContactPage', 'heading', 'Rufen Sie an, oder stellen Sie sich in den Raum'),
  ('de', 'ContactPage', 'intro', 'Ans Telefon geht jemand, der hier arbeitet, kein Dienst, und Sie bekommen beim ersten Anruf eine klare Auskunft über Plätze und Wartelisten. Alles, was Sie brauchen, um uns zu erreichen oder herzufinden, steht auf dieser Seite.'),
  ('de', 'ContactPage', 'mapLabel', 'Kartenplatzhalter — {address}'),
  ('de', 'ContactPage', 'metaDescription', 'Rufen Sie an, schreiben Sie oder kommen Sie vorbei — eine lizenzierte Kindertagesstätte in Northwest Portland: Telefon, Adresse, Öffnungszeiten, Parken und wie Sie mit Bus, Rad oder zu Fuß herkommen.'),
  ('de', 'ContactPage', 'metaTitle', 'Kontakt'),
  ('de', 'ContactPage', 'transitBody', 'Die nächste Bushaltestelle ist drei Gehminuten entfernt, die Straßenbahnlinie etwa acht. Beide lassen Sie auf der Parkseite der Straße aussteigen, sodass Sie einmal und abseits des Verkehrs queren.'),
  ('de', 'ContactPage', 'transitTitle', 'Mit Bus oder Straßenbahn'),
  ('de', 'ContactPage', 'visitBody', 'Sie haben die Nummer und wissen, wo wir sind. Übrig bleibt der Teil, den keine Seite für Sie übernehmen kann: an einem gewöhnlichen Morgen in einem Raum zu stehen und zu entscheiden, ob das die Menschen sind, denen Sie Ihr Kind anvertrauen wollen.'),
  ('de', 'ContactPage', 'visitHeading', 'Der Besuch ist der Teil, der entscheidet'),
  ('de', 'Day', 'arrival', 'Ankommen und Freispiel'),
  ('de', 'Day', 'breakfast', 'Frühstück, dann Morgenkreis'),
  ('de', 'Day', 'centers', 'Lernbereiche und Zeit im Freien'),
  ('de', 'Day', 'lunch', 'Mittagessen aus eigener Küche'),
  ('de', 'Day', 'nap', 'Mittagsschlaf und Ruhezeit'),
  ('de', 'Day', 'pickup', 'Draußen spielen bis zum Abholen'),
  ('de', 'Day', 'snack', 'Snack und Projekte am Nachmittag'),
  ('de', 'FaqPage', 'dailyFoodAnswer', 'Sofia kocht jede Mahlzeit im Haus, weshalb wir bei einer Allergie genau sein können, statt hoffnungsvoll auf ein Etikett zu schauen. Allergien hängen in der Küche und im Gruppenraum aus, und wir bitten Sie nicht, ein eigenes Mittagessen mitzugeben.'),
  ('de', 'FaqPage', 'dailyFoodQuestion', 'Wer kocht, und wie ist es mit Allergien?'),
  ('de', 'FaqPage', 'dailyHeading', 'Von Tag zu Tag'),
  ('de', 'FaqPage', 'dailyNappiesAnswer', 'Im Tempo Ihres Kindes und im Einklang mit dem, was Sie zu Hause tun. Wir werden Ihnen nie sagen, ein Kind müsse windelfrei sein, um die Gruppe zu wechseln, und niemand bekommt das Gefühl, im Rückstand zu sein.'),
  ('de', 'FaqPage', 'dailyNappiesQuestion', 'Wie läuft das Sauberwerden?'),
  ('de', 'FaqPage', 'dailyOutsideAnswer', 'Ja, fast täglich — das hier ist Portland, und ein Jahr drinnen auf trockenes Wetter zu warten ist keine Kindheit. Geben Sie eine Jacke und Stiefel mit, die auch unkenntlich zurückkommen dürfen.'),
  ('de', 'FaqPage', 'dailyOutsideQuestion', 'Gehen sie auch bei Regen raus?'),
  ('de', 'FaqPage', 'dailyScreensAnswer', 'Keine Bildschirme, in keinem Raum, in keinem Alter. Nicht als Regel, auf die wir stolz sind, sondern als eine, die wir nie brechen mussten.'),
  ('de', 'FaqPage', 'dailyScreensQuestion', 'Gibt es Bildschirmzeit?'),
  ('de', 'FaqPage', 'dailySleepAnswer', 'Dann ruht es stattdessen leise mit einem Buch. Kein Kind wird zwei Stunden auf einer Liege gehalten, weil die Gruppe Schlafenszeit hat, und kein Kind wird geweckt, weil das Abholen näher rückt.'),
  ('de', 'FaqPage', 'dailySleepQuestion', 'Was, wenn unser Kind nicht schläft?'),
  ('de', 'FaqPage', 'eyebrow', '{count} Fragen, beantwortet'),
  ('de', 'FaqPage', 'factAgesLabel', 'Alter, das wir aufnehmen'),
  ('de', 'FaqPage', 'factCountLabel', 'Hier beantwortete Fragen'),
  ('de', 'FaqPage', 'factMissingLabel', 'Nicht auf dieser Liste'),
  ('de', 'FaqPage', 'factMissingValue', 'Rufen Sie an und fragen Sie — dann kommt sie dazu'),
  ('de', 'FaqPage', 'factSourceLabel', 'Woher diese stammen'),
  ('de', 'FaqPage', 'factSourceValue', 'Vom Bürotelefon, über etwa ein Jahr'),
  ('de', 'FaqPage', 'heading', 'Die Fragen, die Eltern wirklich stellen'),
  ('de', 'FaqPage', 'intro', 'Diese stammen aus dem Telefon, nicht aus der Fantasie für eine Website. Auch die unangenehmen sind dabei — was passiert, wenn ein Kind beißt, wie man sich über uns beschwert — weil man genau die bei einer Führung nicht stellen kann, ohne sich unhöflich zu fühlen, und weil sich genau die zu wissen lohnt.'),
  ('de', 'FaqPage', 'metaDescription', 'Die Fragen, die Eltern einer lizenzierten Kindertagesstätte in Northwest Portland wirklich stellen — Wartelisten, Eingewöhnung, Essen und Allergien, Krankheit und was passiert, wenn etwas schiefgeht.'),
  ('de', 'FaqPage', 'metaTitle', 'FAQ'),
  ('de', 'FaqPage', 'placeAheadAnswer', 'Für die Säuglingsgruppe, sobald Sie bereit sind, von der Schwangerschaft zu erzählen — diese Gruppe ist sechs bis neun Monate im Rückstand. Plätze bei den Kleinkindern und in der Vorschule bewegen sich schneller, oft innerhalb eines Halbjahres.'),
  ('de', 'FaqPage', 'placeAheadQuestion', 'Wie früh sollten wir uns anmelden?'),
  ('de', 'FaqPage', 'placeDaysAnswer', 'Sie wählen ein Modell statt einzelner Tage: fünf Tage, Montag–Mittwoch–Freitag oder Dienstag–Donnerstag. Feste Tage bedeuten, dass Ihr Kind jedes Mal dieselbe Gruppe um sich hat, und das ist das meiste von dem, was das Einleben ausmacht.'),
  ('de', 'FaqPage', 'placeDaysQuestion', 'Können wir die Tage aussuchen?'),
  ('de', 'FaqPage', 'placeHeading', 'Einen Platz bekommen'),
  ('de', 'FaqPage', 'placeHoldAnswer', 'Ja, bis zu zwei Monate, mit gezahlter Kaution. Länger würde bedeuten, einen leeren Platz zu halten, den eine Familie auf der Liste braucht; dann setzen wir Sie lieber für den Monat, den Sie wirklich wollen, wieder weit nach oben.'),
  ('de', 'FaqPage', 'placeHoldQuestion', 'Können wir einen Platz für einen späteren Start reservieren?'),
  ('de', 'FaqPage', 'placeWaitlistAnswer', 'Nach Gruppe und nach dem Datum, an dem Sie sich eingetragen haben, nicht danach, wer am häufigsten anruft. Wird ein Platz frei, gehen wir die Liste durch, und Sie haben etwa eine Woche zum Entscheiden. Niemand rückt vor, weil er mehr zahlt, und der Eintrag selbst kostet nichts.'),
  ('de', 'FaqPage', 'placeWaitlistQuestion', 'Wie funktioniert die Warteliste?'),
  ('de', 'FaqPage', 'startingBringAnswer', 'Wechselkleidung, eine Jacke, die dreckig werden darf, und das, womit Ihr Kind schläft. Keine Windeln, Feuchttücher, Sonnencreme oder Verpflegung — die sind im Satz enthalten, damit um sieben Uhr morgens niemand hektisch sucht.'),
  ('de', 'FaqPage', 'startingBringQuestion', 'Was müssen wir mitbringen?'),
  ('de', 'FaqPage', 'startingHeading', 'Der Anfang bei uns'),
  ('de', 'FaqPage', 'startingHearAnswer', 'Unter Dreijährige bekommen den Tag aufgeschrieben — jedes Fläschchen, jeden Schlaf, jede Windel — und Sie erhalten ihn beim Abholen. Bei älteren Kindern erzählt ihn die Fachkraft an der Tür, die tatsächlich dabei war, was mehr nützt als ein Formular.'),
  ('de', 'FaqPage', 'startingHearQuestion', 'Wie erfahren wir, wie der Tag unseres Kindes war?'),
  ('de', 'FaqPage', 'startingSettleAnswer', 'Zwei kurze Besuche mit Ihnen im Raum vor dem Startdatum, dann ein halber Tag, dann ein ganzer. Manche Kinder springen gleich zum ganzen Tag, manche brauchen zwei Wochen, und beides ist kein Problem — wir folgen Ihrem Kind, nicht dem Plan.'),
  ('de', 'FaqPage', 'startingSettleQuestion', 'Wie sieht die erste Woche aus?'),
  ('de', 'FaqPage', 'troubleBitingAnswer', 'Beide Elternpaare erfahren es am selben Tag, und keinem wird das andere Kind genannt. Beißen ist in einer Kleinkindgruppe normal, und es ist unsere Aufgabe, zu begleiten und umzulenken, statt von einem Zweijährigen eine Erklärung zu verlangen.'),
  ('de', 'FaqPage', 'troubleBitingQuestion', 'Was, wenn unser Kind beißt oder gebissen wird?'),
  ('de', 'FaqPage', 'troubleComplaintAnswer', 'Sagen Sie es Maria direkt, und Sie bekommen innerhalb von zwei Tagen eine Antwort. Wenn das die Sache nicht klärt, nimmt die staatliche Aufsichtsbehörde Beschwerden über uns entgegen, ganz ohne uns, und wir geben Ihnen die Nummer selbst.'),
  ('de', 'FaqPage', 'troubleComplaintQuestion', 'Wie beschweren wir uns über Sie?'),
  ('de', 'FaqPage', 'troubleHeading', 'Wenn etwas schiefgeht'),
  ('de', 'FaqPage', 'troubleInjuryAnswer', 'Alles über ein aufgeschürftes Knie hinaus bedeutet einen Anruf, während es passiert, keinen Zettel beim Abholen. Jede Verletzung wird dokumentiert, und Sie unterschreiben den Eintrag, auch bei denen, die sich als nichts herausstellen.'),
  ('de', 'FaqPage', 'troubleInjuryQuestion', 'Was passiert, wenn unser Kind sich verletzt?'),
  ('de', 'FaqPage', 'troubleSickAnswer', 'Fieber, Erbrechen oder etwas Ansteckendes heißt nach Hause und vierundzwanzig Stunden beschwerdefrei zu Hause bleiben, nachdem es aufgehört hat. Das ist wirklich unpraktisch, und es ist der Grund, warum nicht in der Woche darauf die ganze Gruppe krank ist.'),
  ('de', 'FaqPage', 'troubleSickQuestion', 'Wann ist ein Kind zu krank zum Kommen?'),
  ('de', 'FaqPage', 'visitBody', 'Eine Liste wie diese beantwortet die Fragen, die uns schon gestellt wurden. Ihre ist vielleicht nicht dabei, und der schnellste Weg dorthin ist, im Haus zu stehen und jemanden zu fragen, der „Das weiß ich nicht, ich finde es heraus“ sagen kann, statt aus einer Seite auszuwählen.'),
  ('de', 'FaqPage', 'visitHeading', 'Den Rest fragen Sie uns persönlich'),
  ('de', 'Footer', 'tagline', 'Lizenzierte Kindertagesstätte · Staatliche Lizenz {licenseNumber} · Für Familien da seit {since}.'),
  ('de', 'HomePage', 'contactAddress', 'Adresse'),
  ('de', 'HomePage', 'contactHours', 'Öffnungszeiten'),
  ('de', 'HomePage', 'contactPhone', 'Telefon'),
  ('de', 'HomePage', 'dayBody', 'Verlässlicher Rhythmus, Platz zum Kindsein. So sehen neun Stunden tatsächlich aus.'),
  ('de', 'HomePage', 'dayHeading', 'Ein Tag bei Willow Grove'),
  ('de', 'HomePage', 'heroBody', 'Eine kleine, lizenzierte Einrichtung in {neighborhood}, in der dieselben Bezugspersonen Ihr Kind jeden Morgen begrüßen und Ihnen genau sagen können, wie sein Tag war.'),
  ('de', 'HomePage', 'heroEyebrow', 'Lizenzierte Kinderbetreuung · Alter {ageRange}'),
  ('de', 'HomePage', 'heroHeading', 'Ein Ort, an dem Ihr Kind beim Namen gekannt wird.'),
  ('de', 'HomePage', 'infantsBlurb', 'Eine feste Bezugsperson pro Kind, damit Fläschchen, Schlaf und erste Wörter von jemandem verfolgt werden, der Ihr Baby kennt — nicht von dem, der gerade frei ist.'),
  ('de', 'HomePage', 'mapLabel', 'Karte von {neighborhood}'),
  ('de', 'HomePage', 'metaDescription', 'Eine kleine, lizenzierte Kindertagesstätte in Northwest Portland für Kinder von 6 Wochen bis 5 Jahren, in der dieselben Bezugspersonen Ihr Kind beim Namen kennen. Rufen Sie an und planen Sie einen Besuch.'),
  ('de', 'HomePage', 'metaTitle', 'Willow Grove Children''s Center · Lizenzierte Kinderbetreuung in NW Portland'),
  ('de', 'HomePage', 'planVisit', 'Besuch planen'),
  ('de', 'HomePage', 'preschoolBlurb', 'Erste Schrift, Zahlen und die schwierigere Arbeit des Abwartens und des Benennens von Gefühlen — die Grundlage für die Grundschule.'),
  ('de', 'HomePage', 'programsHeading', 'Programme nach Alter'),
  ('de', 'HomePage', 'staffHeading', 'Die Menschen, die Ihr Kind kennen werden'),
  ('de', 'HomePage', 'testimonialAttribution', 'Priya R., Mutter eines Kindes aus der Säuglingsgruppe'),
  ('de', 'HomePage', 'testimonialHeading', 'Von einer Mutter'),
  ('de', 'HomePage', 'testimonialQuote', '„Am dritten Tag sagte mir Aisha, dass meine Tochter nur einschläft, wenn sie den blauen Elefanten halten kann. Das hatte ich niemandem erzählt. Da hörte ich auf, mir Sorgen zu machen.“'),
  ('de', 'HomePage', 'toddlersBlurb', 'Platz zum Bewegen und Sprache überall. Die Tage sind vorhersehbar, damit ein Kleinkind, das die Welt lernt, sich darauf verlassen kann, was als Nächstes kommt.'),
  ('de', 'HomePage', 'trustInfantRatio', 'Schlüssel Säuglinge'),
  ('de', 'HomePage', 'trustOpenWeekdays', 'Werktags geöffnet'),
  ('de', 'HomePage', 'trustStateLicense', 'Staatliche Lizenz'),
  ('de', 'HomePage', 'trustYearsCaring', 'Für Familien da'),
  ('de', 'HomePage', 'visitHeading', 'Kommen Sie und sehen Sie selbst'),
  ('de', 'HomePage', 'yearsValue', '{years} Jahre'),
  ('de', 'Nav', 'about', 'Über uns'),
  ('de', 'Nav', 'contact', 'Kontakt'),
  ('de', 'Nav', 'faq', 'FAQ'),
  ('de', 'Nav', 'home', 'Willow Grove Startseite'),
  ('de', 'Nav', 'programs', 'Programme'),
  ('de', 'Nav', 'staff', 'Team'),
  ('de', 'Nav', 'tuition', 'Gebühren'),
  ('de', 'Programs', 'infants', 'Säuglinge'),
  ('de', 'Programs', 'infantsAges', '6 Wochen – 15 Monate'),
  ('de', 'Programs', 'infantsGroupSize', '8 Kinder'),
  ('de', 'Programs', 'preschool', 'Vorschule'),
  ('de', 'Programs', 'preschoolAges', '3 – 5 Jahre'),
  ('de', 'Programs', 'preschoolGroupSize', '18 Kinder'),
  ('de', 'Programs', 'toddlers', 'Kleinkinder'),
  ('de', 'Programs', 'toddlersAges', '15 Monate – 3 Jahre'),
  ('de', 'Programs', 'toddlersGroupSize', '10 Kinder'),
  ('de', 'ProgramsPage', 'dayBody', 'Jede Gruppe folgt demselben Rhythmus, dem Alter angepasst. Säuglinge schlafen und essen darin nach ihrem eigenen Plan; ältere Kinder gehen gemeinsam hindurch.'),
  ('de', 'ProgramsPage', 'dayHeading', 'Ein Tag bei Willow Grove'),
  ('de', 'ProgramsPage', 'eyebrow', 'Alter {ageRange}'),
  ('de', 'ProgramsPage', 'factAges', 'Alter'),
  ('de', 'ProgramsPage', 'factGroup', 'Gruppengröße'),
  ('de', 'ProgramsPage', 'factRatio', 'Schlüssel'),
  ('de', 'ProgramsPage', 'heading', 'Programme nach Alter'),
  ('de', 'ProgramsPage', 'infantsDetail', 'Jedes Baby bekommt eine feste Bezugsperson, die Fläschchen, Schlaf und Wickeln übernimmt. Das ist die Person, die lernt, dass Ihre Tochter nur mit dem blauen Elefanten einschläft, und die Ihnen beim Abholen davon erzählt.'),
  ('de', 'ProgramsPage', 'infantsStaffing', 'Essen und Schlaf richten sich nach dem Rhythmus Ihres Babys, nicht nach dem der Gruppe. Sie bekommen den Tag aufgeschrieben — jedes Fläschchen, jeden Schlaf, jede Windel — bevor Sie am Auto sind.'),
  ('de', 'ProgramsPage', 'intro', 'Drei Gruppen in einem Haus und dieselben Gesichter von der Säuglingsgruppe bis zu dem Morgen, an dem Ihr Kind in die Grundschule geht. Hier steht, wer in welcher Gruppe ist, wie viele Kinder betreut werden und was der Tag bereithält.'),
  ('de', 'ProgramsPage', 'metaDescription', 'Gruppen für Säuglinge, Kleinkinder und Vorschulkinder in Northwest Portland — Betreuungsschlüssel, Gruppengrößen und wie ein Tag in jeder Gruppe wirklich aussieht.'),
  ('de', 'ProgramsPage', 'metaTitle', 'Programme'),
  ('de', 'ProgramsPage', 'preschoolDetail', 'Erste Schrift und Zahlen — und der schwierigere Lehrplan darunter: abwarten, teilen, sagen was man fühlt, statt etwas zu werfen. Das ist die Grundlage, mit der die Grundschule rechnet.'),
  ('de', 'ProgramsPage', 'preschoolStaffing', 'Jeden Morgen Kleingruppenarbeit, geleitet von einer Fachkraft, die diese Gruppe seit Jahren unterrichtet. Im Frühjahr schreiben wir an die Grundschule Ihres Kindes, damit die erste Lehrkraft es schon kennt.'),
  ('de', 'ProgramsPage', 'toddlersDetail', 'Das Jahr, in dem ein Kind lernt, dass die Welt eine Ordnung hat. Die Tage sind bewusst vorhersehbar, damit ein Kleinkind, das die Uhr noch nicht lesen kann, trotzdem weiß, was als Nächstes kommt — und die Sprache hört nie auf: benennen, erzählen, fragen.'),
  ('de', 'ProgramsPage', 'toddlersStaffing', 'Zwei Fachkräfte bleiben das ganze Jahr in dieser Gruppe. Das Sauberwerden geschieht im Tempo Ihres Kindes und im Einklang mit dem, was Sie zu Hause tun, nie nach einer Frist, die wir setzen.'),
  ('de', 'ProgramsPage', 'visitAria', 'Besuch planen'),
  ('de', 'ProgramsPage', 'visitBody', 'Rufen Sie im Büro an, und Sie bekommen eine klare Auskunft darüber, welche Gruppen Platz haben und wie lang die Wartezeit für die anderen ist — und dann kommen Sie und stellen sich in den Raum, in dem Ihr Kind tatsächlich wäre.'),
  ('de', 'ProgramsPage', 'visitHeading', 'Unsicher, welche Gruppe passt?'),
  ('de', 'Staff', 'aishaBio', 'Acht Jahre in der Säuglingsgruppe, und noch nie hat sie Eltern ein Tagesblatt in die Hand gedrückt, bei dem sie raten musste. Sie ist der Grund, warum wir Ihnen sagen können, auf welcher Seite Ihre Tochter lieber gehalten wird.'),
  ('de', 'Staff', 'aishaRole', 'Leitung Säuglingsgruppe'),
  ('de', 'Staff', 'danielBio', 'Verbringt seinen Tag damit, die Welt Menschen zu erklären, die gerade entdeckt haben, dass sie Wörter hat. Das Sauberwerden geschieht bei ihm, im Tempo Ihres Kindes, und er wird Ihnen nie das Gefühl geben, im Rückstand zu sein.'),
  ('de', 'Staff', 'danielRole', 'Leitung Kleinkindgruppe'),
  ('de', 'Staff', 'graceBio', 'Kam von einer Neugeborenenstation im Krankenhaus zu uns, was man daran merkt, wie sie mit einem Baby umgeht, das nicht zur Ruhe kommt. Sie hat die ruhigsten Hände im Haus, und der Raum ist dadurch leiser.'),
  ('de', 'Staff', 'graceRole', 'Erzieherin Säuglingsgruppe'),
  ('de', 'Staff', 'mariaBio', 'Führt das Haus und übernimmt immer noch die Säuglingsgruppe, wenn jemand krank ist. Sie ist die Person, zu der Sie durchgestellt werden, wenn Sie anrufen, und die Ihnen offen sagt, wenn für die gewünschte Gruppe neun Monate Wartezeit bestehen.'),
  ('de', 'Staff', 'mariaRole', 'Leiterin'),
  ('de', 'Staff', 'nadiaBio', 'Kümmert sich um Anmeldungen, die Warteliste und jedes Formular, das die Behörde verlangt. Wenn Ihnen anderswo je eine vage Auskunft über Gebühren gegeben wurde, ist sie die Korrektur dazu.'),
  ('de', 'Staff', 'nadiaRole', 'Stellvertretende Leiterin'),
  ('de', 'Staff', 'sofiaBio', 'Kocht jede Mahlzeit im Haus, weshalb wir bei Allergien genau sein können statt nur hoffnungsvoll. Sie weiß, welche Kinder Gemüse nur essen, wenn es auf eine bestimmte Art geschnitten ist, und schneidet es genau so.'),
  ('de', 'Staff', 'sofiaRole', 'Köchin'),
  ('de', 'Staff', 'tenure', 'seit {years} Jahren bei Willow Grove'),
  ('de', 'Staff', 'tomBio', 'Leitet jeden Morgen die Kleingruppenarbeit und schreibt im Frühjahr an die Grundschule jedes Kindes, damit die erste Lehrkraft es schon kennt. Sechs Jahre in derselben Gruppe.'),
  ('de', 'Staff', 'tomRole', 'Leitung Vorschulgruppe'),
  ('de', 'StaffPage', 'eyebrow', '{count} Personen im Team'),
  ('de', 'StaffPage', 'factChecksLabel', 'Jede Einstellung'),
  ('de', 'StaffPage', 'factChecksValue', 'Führungszeugnis geprüft, Erste Hilfe und Reanimation aktuell'),
  ('de', 'StaffPage', 'factLongestLabel', 'Am längsten bei uns'),
  ('de', 'StaffPage', 'factTeamLabel', 'Personen im Team'),
  ('de', 'StaffPage', 'factTenureLabel', 'Durchschnittlich bei uns'),
  ('de', 'StaffPage', 'heading', 'Die Menschen, die Ihr Kind kennen werden'),
  ('de', 'StaffPage', 'intro', 'Die Führung erzählt Ihnen etwas über das Gebäude. Diese Seite erzählt Ihnen etwas über die Menschen darin, denn ein Raum ist nur so verlässlich wie die Person, die darin steht — und wie lange sie geblieben ist, kann keine Broschüre erfinden.'),
  ('de', 'StaffPage', 'metaDescription', 'Die Erzieherinnen, Erzieher und Mitarbeitenden einer lizenzierten Kindertagesstätte in Northwest Portland — wer sie sind, wie lange sie schon hier sind und warum das die Zahl zum Vergleichen ist.'),
  ('de', 'StaffPage', 'metaTitle', 'Team'),
  ('de', 'StaffPage', 'stayBody', 'Personalwechsel ruiniert eine Einrichtung leise, und auf einer Website wird er fast nie erwähnt. Hier steht, was wir dagegen tun, damit Sie der nächsten Einrichtung dieselben drei Fragen stellen können.'),
  ('de', 'StaffPage', 'stayHeading', 'Warum Menschen bleiben'),
  ('de', 'StaffPage', 'stayHiringBody', 'Eine offene Stelle wird von der Leitung und der stellvertretenden Leitung abgedeckt, statt schnell besetzt zu werden. Bei jeder Einstellung liegt vor dem ersten Tag mit Kindern ein Führungszeugnis vor, ohne Ausnahmen für volle Wochen.'),
  ('de', 'StaffPage', 'stayHiringTitle', 'Absichtlich langsam bei Einstellungen'),
  ('de', 'StaffPage', 'stayPayBody', 'Unsere Fachkräfte verdienen mehr als in den Einrichtungen um uns herum, und die Bezahlung steigt mit der Zeit hier statt mit einem Titel. Das ist der größte Posten auf unserer Kostenaufstellung und der Grund, warum die Gebühren sind, wie sie sind.'),
  ('de', 'StaffPage', 'stayPayTitle', 'Bewusst über dem üblichen Satz bezahlt'),
  ('de', 'StaffPage', 'stayRoomBody', 'Niemand wird zwischen Gruppen verschoben, um eine Lücke zu stopfen. Eine Fachkraft bleibt das Jahr über bei ihrer Gruppe, und erst das macht aus einer festen Bezugsperson mehr als ein Wort auf dem Papier.'),
  ('de', 'StaffPage', 'stayRoomTitle', 'Dieselbe Gruppe, das ganze Jahr'),
  ('de', 'StaffPage', 'teamBody', 'Porträts folgen; die Initialen sind ein Platzhalter, kein Stockfoto vom Personal einer anderen Einrichtung. Alles unter jedem Namen trifft auf die Person zu, die tatsächlich im Raum stehen wird.'),
  ('de', 'StaffPage', 'teamHeading', 'Wer hier ist'),
  ('de', 'StaffPage', 'visitBody', 'Namen auf einer Seite nützen wenig. Kommen Sie vorbei, schauen Sie sich die Gruppe an, in der Ihr Kind wäre, und sehen Sie, ob die Person darin jemand ist, bei dem Ihr Kind zur Ruhe käme.'),
  ('de', 'StaffPage', 'visitHeading', 'Kommen Sie vorbei und lernen Sie sie kennen'),
  ('de', 'StaffPage', 'yearsValue', '{years} Jahre'),
  ('de', 'TuitionPage', 'eyebrow', 'Ab {lowest} im Monat, Vollzeit'),
  ('de', 'TuitionPage', 'factDepositLabel', 'Kaution'),
  ('de', 'TuitionPage', 'factDepositValue', '{weeks} Wochen, erstattet beim Austritt'),
  ('de', 'TuitionPage', 'factIncludedLabel', 'Im Satz enthalten'),
  ('de', 'TuitionPage', 'factIncludedValue', 'Mahlzeiten, Snacks, Windeln, Feuchttücher und Sonnencreme'),
  ('de', 'TuitionPage', 'factNoticeLabel', 'Kündigungsfrist'),
  ('de', 'TuitionPage', 'factNoticeValue', '{weeks} Wochen, schriftlich'),
  ('de', 'TuitionPage', 'factRegistrationLabel', 'Anmeldung'),
  ('de', 'TuitionPage', 'factRegistrationValue', '{amount}, einmalig bei der Aufnahme'),
  ('de', 'TuitionPage', 'fiveDayBody', 'Die ganze Woche, und das einzige Modell, bei dem Ihr Kind jeden Tag dieselbe Gruppe um sich hat. Für Säuglinge empfehlen wir es, weil sie sich schneller einleben, wenn die Woche nicht ständig die Form wechselt.'),
  ('de', 'TuitionPage', 'fiveDayDays', 'Montag bis Freitag'),
  ('de', 'TuitionPage', 'fiveDayName', 'Fünf Tage'),
  ('de', 'TuitionPage', 'heading', 'Was ein Platz hier kostet'),
  ('de', 'TuitionPage', 'hiddenBody', 'Nichts davon steckt in einem Vertrag, den Sie am letzten Tag unterschreiben. Es steht hier, bevor Sie anrufen, weil die Kosten von Kinderbetreuung nicht nur die Zahl in der Tabelle sind.'),
  ('de', 'TuitionPage', 'hiddenClosuresBody', 'Gesetzliche Feiertage, dazu drei Fortbildungstage im Jahr und die Woche zwischen Weihnachten und Neujahr. Diese werden berechnet — der Satz gilt monatlich, nicht pro besuchtem Tag — und die Termine werden jeden August ein Jahr im Voraus veröffentlicht.'),
  ('de', 'TuitionPage', 'hiddenClosuresTitle', 'Tage, an denen wir geschlossen sind'),
  ('de', 'TuitionPage', 'hiddenHeading', 'Die Teile, die eine Preisliste sonst weglässt'),
  ('de', 'TuitionPage', 'hiddenHelpBody', 'Wir akzeptieren staatliche Zuschüsse und nehmen Betreuungszuschüsse von Arbeitgebern an. Nadia kümmert sich um beides und sagt Ihnen, wofür Sie voraussichtlich infrage kommen, bevor Sie irgendetwas ausfüllen — auch dann, wenn die Antwort nichts ist.'),
  ('de', 'TuitionPage', 'hiddenHelpTitle', 'Hilfe bei den Kosten'),
  ('de', 'TuitionPage', 'hiddenIncreaseBody', 'Die Sätze steigen einmal im Jahr, meist um wenige Prozent, entsprechend dem, was wir den Fachkräften zahlen. Sie bekommen es im Juni schriftlich für einen Start im September, damit niemand von einer Rechnung überrascht wird.'),
  ('de', 'TuitionPage', 'hiddenIncreaseTitle', 'Die jährliche Erhöhung'),
  ('de', 'TuitionPage', 'hiddenLateBody', '{amount} pro Minute nach achtzehn Uhr, in vollen Minuten berechnet und der nächsten Rechnung zugeschlagen. Das ist keine Strafe; es ist, was es kostet, zwei Mitarbeitende im Haus zu halten, und zwei sind das Minimum, das die Lizenz erlaubt.'),
  ('de', 'TuitionPage', 'hiddenLateTitle', 'Verspätetes Abholen'),
  ('de', 'TuitionPage', 'hiddenSiblingBody', '{percent}% Nachlass auf den Satz des jüngeren Kindes, automatisch, solange beide angemeldet sind. Sie müssen nicht danach fragen, und niemand muss daran denken, ihn einzutragen.'),
  ('de', 'TuitionPage', 'hiddenSiblingTitle', 'Zwei Kinder bei uns'),
  ('de', 'TuitionPage', 'intro', 'Bei den meisten Einrichtungen müssen Sie dafür anrufen. Uns ist lieber, Sie sehen die Zahl jetzt und entscheiden, ob sie einen Anruf wert ist, als dass Sie es am Ende einer Führung erfahren, für die Sie einen Vormittag aufgewendet haben. Jeder Satz, den wir verlangen, steht auf dieser Seite.'),
  ('de', 'TuitionPage', 'metaDescription', 'Was Kinderbetreuung in Northwest Portland wirklich kostet — Monatssätze für jede Gruppe und jedes Modell, offen auf der Seite, samt der Kosten, die eine Preisliste sonst weglässt.'),
  ('de', 'TuitionPage', 'metaTitle', 'Gebühren'),
  ('de', 'TuitionPage', 'ratesBody', 'Die Sätze gelten monatlich und ändern sich nicht mit der Länge des Monats — im Februar zahlen Sie dasselbe wie im März. Ein Teilzeitplatz kostet pro Tag mehr als ein Vollzeitplatz, weil die Gruppe die ganze Woche besetzt ist, ob Ihr Kind an dem Tag da ist oder nicht.'),
  ('de', 'TuitionPage', 'ratesFootnote', 'Die Sätze werden einmal im Jahr im September überprüft, und wir teilen es Ihnen schriftlich bis zum Juni davor mit — nie mitten im Jahr und nie mit weniger als einem Halbjahr Vorlauf.'),
  ('de', 'TuitionPage', 'ratesHeading', 'Monatssätze'),
  ('de', 'TuitionPage', 'ratesRoom', 'Gruppe'),
  ('de', 'TuitionPage', 'ratesTableCaption', 'Monatsgebühren nach Gruppe und Modell'),
  ('de', 'TuitionPage', 'schedulesBody', 'Drei Modelle, an festen Tagen. Sie können wechseln, sobald im gewünschten Modell ein Platz frei wird, und behalten währenddessen Ihren Platz auf der Liste.'),
  ('de', 'TuitionPage', 'schedulesHeading', 'Betreuungsmodelle'),
  ('de', 'TuitionPage', 'schedulesSwitching', 'Ein Wechsel braucht einen Monat Vorlauf und einen freien Platz in der Gruppe an den Tagen, auf die Sie wechseln. Wir sagen Ihnen ehrlich, ob das Wochen entfernt ist oder fast ein Jahr.'),
  ('de', 'TuitionPage', 'threeDayBody', 'Feste Tage statt Tage, die Sie jede Woche neu wählen, damit Ihr Kind weiß, welche Morgen ihm gehören, und die Gruppe beständig bleibt. Die meisten Familien in diesem Modell teilen sich die Woche mit den Großeltern.'),
  ('de', 'TuitionPage', 'threeDayDays', 'Montag, Mittwoch, Freitag'),
  ('de', 'TuitionPage', 'threeDayName', 'Drei Tage'),
  ('de', 'TuitionPage', 'twoDayBody', 'Genug, um eine Routine und eine Freundschaft zu halten, ohne die ganze Woche. Plätze in diesem Modell sind die knappsten, die wir haben, weil zwei davon einen Vollzeitplatz füllen und beide zusammenpassen müssen.'),
  ('de', 'TuitionPage', 'twoDayDays', 'Dienstag und Donnerstag'),
  ('de', 'TuitionPage', 'twoDayName', 'Zwei Tage'),
  ('de', 'TuitionPage', 'visitBody', 'Sie haben die Zahlen, und das ist das meiste von dem, was eine Führung Ihnen über Geld gesagt hätte. Offen bleibt, ob der Raum es wert ist, und genau das kann eine Preisliste Ihnen nicht zeigen.'),
  ('de', 'TuitionPage', 'visitHeading', 'Vor der Entscheidung einen Anruf wert'),
  ('de', 'Visit', 'askLabel', 'Fragen Sie nach'),
  ('de', 'Visit', 'askValue', 'Maria, der Leiterin'),
  ('de', 'Visit', 'bookingLabel', 'Anmeldung'),
  ('de', 'Visit', 'bookingValue', 'Kein Termin nötig'),
  ('de', 'Visit', 'call', 'Anrufen'),
  ('de', 'Visit', 'cardHeading', 'So läuft ein Besuch ab'),
  ('de', 'Visit', 'lengthLabel', 'Wie lange es dauert'),
  ('de', 'Visit', 'lengthValue', 'Etwa zwanzig Minuten'),
  ('de', 'Visit', 'whenLabel', 'Beste Zeit zum Kommen'),
  ('de', 'Visit', 'whenValue', 'Zehn Uhr morgens, wenn die Gruppen laufen'),
  ('en', 'AboutPage', 'eyebrow', 'Licensed since {since}'),
  ('en', 'AboutPage', 'heading', 'How we care for children, and why'),
  ('en', 'AboutPage', 'intro', 'A center is easy to describe well and hard to run well. This page is the second thing — how the rooms are staffed, what the license behind the front door actually covers, and what happens on the ordinary days nobody writes a brochure about.'),
  ('en', 'AboutPage', 'licensingBody', 'We have held a state child care license continuously since {since}. A license is not a certificate on a wall; it is an inspection regime, and we would rather you know exactly what it covers before you ask.'),
  ('en', 'AboutPage', 'licensingCoversBuilding', 'Building, playground, exits, and drills'),
  ('en', 'AboutPage', 'licensingCoversHeading', 'What an inspection covers'),
  ('en', 'AboutPage', 'licensingCoversKitchen', 'The kitchen, food handling, and allergy practice'),
  ('en', 'AboutPage', 'licensingCoversRatios', 'Ratios and supervision, room by room'),
  ('en', 'AboutPage', 'licensingCoversRecords', 'Staff files, clearances, and training records'),
  ('en', 'AboutPage', 'licensingCoversSleep', 'Safe sleep, cots, and nap routines'),
  ('en', 'AboutPage', 'licensingHeading', 'Licensing and the checks behind it'),
  ('en', 'AboutPage', 'licensingInspectionsLabel', 'Inspections'),
  ('en', 'AboutPage', 'licensingInspectionsValue', 'Unannounced, at least annually'),
  ('en', 'AboutPage', 'licensingNumberLabel', 'State license'),
  ('en', 'AboutPage', 'licensingRecords', 'The state keeps our full inspection history, and you are entitled to read it. Ask at the office and we will show you ours, findings included.'),
  ('en', 'AboutPage', 'licensingSinceLabel', 'Licensed since'),
  ('en', 'AboutPage', 'licensingStaffLine', 'Every member of staff is background-checked before their first day with children, and holds current CPR and first aid certification — the director included.'),
  ('en', 'AboutPage', 'metaDescription', 'A licensed child care center in Northwest Portland since {since} — our approach, our ratios, our state license, and what safety looks like on an ordinary day.'),
  ('en', 'AboutPage', 'metaTitle', 'About'),
  ('en', 'AboutPage', 'philosophyHeading', 'What we believe'),
  ('en', 'AboutPage', 'philosophyKnownBody', 'Every child has a primary caregiver, and teachers stay with their room for the year. It is why we can tell you at pickup that your son ate half his lunch and then fell asleep on the reading cushion — someone was there for all of it.'),
  ('en', 'AboutPage', 'philosophyKnownTitle', 'A child should be known by a few people, not minded by many'),
  ('en', 'AboutPage', 'philosophyPlainBody', 'If your child bit someone, we will tell you. If a room is full and the wait is nine months, we will say nine months rather than let you hope. You cannot leave your child somewhere you have caught being vague.'),
  ('en', 'AboutPage', 'philosophyPlainTitle', 'Parents get the truth, including the parts that are hard'),
  ('en', 'AboutPage', 'philosophyRhythmBody', 'The same rhythm every day — arrival, breakfast, circle, outside, lunch, rest. A child who knows what comes next has the confidence to be inventive inside it. Structure is what makes the mess possible.'),
  ('en', 'AboutPage', 'philosophyRhythmTitle', 'The day should be predictable, the play should not'),
  ('en', 'AboutPage', 'ratiosAges', 'Ages'),
  ('en', 'AboutPage', 'ratiosBody', 'These are the numbers we staff to every hour we are open, not an average across the week. Both matter: the ratio is how much attention your child gets, and the group size is how loud and how busy the room is around them.'),
  ('en', 'AboutPage', 'ratiosFootnote', 'Our ratios are at or below what the state requires for each age, and we hold them through nap, lunch, and the end of the day — the hours a ratio is easiest to quietly let slip.'),
  ('en', 'AboutPage', 'ratiosGroup', 'Group size'),
  ('en', 'AboutPage', 'ratiosHeading', 'Ratios and group sizes'),
  ('en', 'AboutPage', 'ratiosRatio', 'Ratio'),
  ('en', 'AboutPage', 'ratiosRoom', 'Room'),
  ('en', 'AboutPage', 'ratiosTableCaption', 'Staffing ratio and group size by room'),
  ('en', 'AboutPage', 'safetyAllergyBody', 'Allergies are posted in the room and in the kitchen, meals are made on site so we control what is in them, and medication is given only with your written instruction and logged when it is.'),
  ('en', 'AboutPage', 'safetyAllergyTitle', 'Allergies and medication'),
  ('en', 'AboutPage', 'safetyBody', 'Most of safety is not dramatic. It is the same small routines done the same way every day, by people who are not improvising.'),
  ('en', 'AboutPage', 'safetyDrillsBody', 'Fire drills monthly and emergency procedures quarterly, with the children, so the routine is familiar to them rather than frightening.'),
  ('en', 'AboutPage', 'safetyDrillsTitle', 'Practised, not planned'),
  ('en', 'AboutPage', 'safetyEntryBody', 'A single entrance with a keypad code, changed each term. Nobody who is not on your child''s authorized list leaves with them — no exceptions made at the door, ever, however plausible the person seems.'),
  ('en', 'AboutPage', 'safetyEntryTitle', 'One locked door'),
  ('en', 'AboutPage', 'safetyHeading', 'Safety, on an ordinary day'),
  ('en', 'AboutPage', 'safetyIllnessBody', 'Fever, vomiting, or anything contagious means going home and staying home for twenty-four clear hours. It is inconvenient, and it is the reason the whole room is not sick next week.'),
  ('en', 'AboutPage', 'safetyIllnessTitle', 'Illness, said plainly'),
  ('en', 'AboutPage', 'safetySignInBody', 'Every child is signed in and out by name, and teachers count their group at every transition — into the room, out to the yard, back from the yard.'),
  ('en', 'AboutPage', 'safetySignInTitle', 'Signed in and counted'),
  ('en', 'AboutPage', 'visitAria', 'Plan a visit'),
  ('en', 'AboutPage', 'visitBody', 'None of this is worth much on a screen. Every center looks calm at nap time; what you want to see is a room with children awake in it, and the only way to see that is to be standing in one.'),
  ('en', 'AboutPage', 'visitHeading', 'The part that matters is standing in the room'),
  ('en', 'Center', 'ageRange', '6 weeks to 5 years'),
  ('en', 'Center', 'hoursCompact', '7am–6pm'),
  ('en', 'Center', 'hoursShort', 'Mon–Fri, 7:00 AM – 6:00 PM'),
  ('en', 'Center', 'neighborhood', 'Northwest Portland, one block from Wallace Park'),
  ('en', 'ContactPage', 'callBody', 'One number reaches all of it. Saying which of these it is when someone picks up gets you to the right person faster.'),
  ('en', 'ContactPage', 'callHeading', 'What to call about, and who you will get'),
  ('en', 'ContactPage', 'callHoursBody', 'Voicemail after six, picked up when the office opens at seven the next morning. Nothing is answered overnight, so if it cannot wait until then, it should not be a message.'),
  ('en', 'ContactPage', 'callHoursTitle', 'Outside opening hours'),
  ('en', 'ContactPage', 'callIllnessBody', 'Call before nine so the room can plan its morning. Tell us the symptom rather than the diagnosis; whether it is a twenty-four-hour exclusion is our job to work out, not yours.'),
  ('en', 'ContactPage', 'callIllnessTitle', 'Your child is unwell today'),
  ('en', 'ContactPage', 'callPlaceBody', 'Ask for Nadia, who keeps the waiting list. She will tell you which rooms have space and, if the one you want does not, how long the wait honestly is — including when the answer is most of a year.'),
  ('en', 'ContactPage', 'callPlaceTitle', 'A place for your child'),
  ('en', 'ContactPage', 'drivingBody', 'Four marked spaces beside the building are reserved for drop-off and pickup, fifteen minutes each. Street parking on the block is unrestricted, and the far end is usually open even at half past eight.'),
  ('en', 'ContactPage', 'drivingTitle', 'Driving and parking'),
  ('en', 'ContactPage', 'emailNote', 'Email is read once a day, in the afternoon. For anything about a place, a start date, or a child who is unwell, please call — you will get an answer in the same conversation rather than tomorrow.'),
  ('en', 'ContactPage', 'eyebrow', 'One number, one address'),
  ('en', 'ContactPage', 'factAddressLabel', 'Address'),
  ('en', 'ContactPage', 'factClosedLabel', 'Closed'),
  ('en', 'ContactPage', 'factClosedValue', 'Weekends and public holidays'),
  ('en', 'ContactPage', 'factEmailLabel', 'Email'),
  ('en', 'ContactPage', 'factHoursLabel', 'Open'),
  ('en', 'ContactPage', 'footBody', 'One block from Wallace Park, with a covered bike rack inside the gate. Buggies and strollers go in the entry hall rather than the rooms — there is space for them, and it keeps the doorways clear.'),
  ('en', 'ContactPage', 'footTitle', 'On foot and by bike'),
  ('en', 'ContactPage', 'gettingHereBody', 'We are on a residential block, which is lovely at eight in the morning and awkward if you are circling for a space. Here is what the school run actually looks like, so your first drop-off is not also your first time working it out.'),
  ('en', 'ContactPage', 'gettingHereHeading', 'Getting here'),
  ('en', 'ContactPage', 'heading', 'Call us, or come and stand in the room'),
  ('en', 'ContactPage', 'intro', 'The phone is answered by someone who works here, not a service, and you will get a plain answer about space and waiting lists on the first call. Everything you need to reach us or find us is on this page.'),
  ('en', 'ContactPage', 'mapLabel', 'Map placeholder — {address}'),
  ('en', 'ContactPage', 'metaDescription', 'Call, email, or visit a licensed child care center in Northwest Portland — phone, address, opening hours, parking, and how to get here by bus, bike, or on foot.'),
  ('en', 'ContactPage', 'metaTitle', 'Contact'),
  ('en', 'ContactPage', 'transitBody', 'The nearest bus stop is a three-minute walk, and the streetcar line is about eight minutes on foot. Both leave you on the park side of the street, so you cross once and away from traffic.'),
  ('en', 'ContactPage', 'transitTitle', 'By bus or streetcar'),
  ('en', 'ContactPage', 'visitBody', 'You have the number and you know where we are. What is left is the part no page can do for you: standing in a room on an ordinary morning and deciding whether these are the people you want holding your child.'),
  ('en', 'ContactPage', 'visitHeading', 'The visit is the part that decides it'),
  ('en', 'Day', 'arrival', 'Arrival and free play'),
  ('en', 'Day', 'breakfast', 'Breakfast, then morning circle'),
  ('en', 'Day', 'centers', 'Learning centers and outdoor time'),
  ('en', 'Day', 'lunch', 'Lunch, made on site'),
  ('en', 'Day', 'nap', 'Nap and quiet rest'),
  ('en', 'Day', 'pickup', 'Outdoor play until pickup'),
  ('en', 'Day', 'snack', 'Snack and afternoon projects'),
  ('en', 'FaqPage', 'dailyFoodAnswer', 'Sofia cooks every meal on site, which is why we can be exact about an allergy rather than hopeful about a label. Allergies are posted in the kitchen and in the room, and we do not ask you to send a separate lunch.'),
  ('en', 'FaqPage', 'dailyFoodQuestion', 'Who cooks, and what about allergies?'),
  ('en', 'FaqPage', 'dailyHeading', 'Day to day'),
  ('en', 'FaqPage', 'dailyNappiesAnswer', 'On your child''s timeline and in step with whatever you are doing at home. We will never tell you a child has to be out of nappies to move rooms, and nobody is made to feel behind.'),
  ('en', 'FaqPage', 'dailyNappiesQuestion', 'How does toilet learning work?'),
  ('en', 'FaqPage', 'dailyOutsideAnswer', 'Yes, most days — this is Portland, and a year indoors waiting for dry weather is not a childhood. Send a coat and boots that you do not mind coming home unrecognisable.'),
  ('en', 'FaqPage', 'dailyOutsideQuestion', 'Do they go outside when it rains?'),
  ('en', 'FaqPage', 'dailyScreensAnswer', 'No screens in any room, at any age. Not as a rule we are proud of, just one we have never needed to break.'),
  ('en', 'FaqPage', 'dailyScreensQuestion', 'Is there screen time?'),
  ('en', 'FaqPage', 'dailySleepAnswer', 'They rest quietly with a book instead. No child is kept on a cot for two hours because the room has a nap time, and no child is woken because pickup is coming.'),
  ('en', 'FaqPage', 'dailySleepQuestion', 'What if our child does not nap?'),
  ('en', 'FaqPage', 'eyebrow', '{count} questions, answered'),
  ('en', 'FaqPage', 'factAgesLabel', 'Ages we take'),
  ('en', 'FaqPage', 'factCountLabel', 'Questions answered here'),
  ('en', 'FaqPage', 'factMissingLabel', 'Not on this list'),
  ('en', 'FaqPage', 'factMissingValue', 'Call and ask — it gets added'),
  ('en', 'FaqPage', 'factSourceLabel', 'Where these came from'),
  ('en', 'FaqPage', 'factSourceValue', 'The office phone, over about a year'),
  ('en', 'FaqPage', 'heading', 'The questions parents actually ask'),
  ('en', 'FaqPage', 'intro', 'These are taken from the phone, not invented for a website. They include the awkward ones — what happens when a child bites, how to complain about us — because those are the ones you cannot ask on a tour without feeling rude, and they are the ones worth knowing the answer to.'),
  ('en', 'FaqPage', 'metaDescription', 'The questions parents actually ask a licensed child care center in Northwest Portland — waiting lists, settling in, food and allergies, illness, and what happens when something goes wrong.'),
  ('en', 'FaqPage', 'metaTitle', 'FAQ'),
  ('en', 'FaqPage', 'placeAheadAnswer', 'For the infant room, as soon as you are ready to tell people you are expecting — that room runs six to nine months behind. Toddler and preschool places move faster, often within a term.'),
  ('en', 'FaqPage', 'placeAheadQuestion', 'How far ahead should we apply?'),
  ('en', 'FaqPage', 'placeDaysAnswer', 'You choose a schedule rather than individual days: five days, Monday–Wednesday–Friday, or Tuesday–Thursday. Fixed days mean your child has the same group around them each time, which is most of what makes them settle.'),
  ('en', 'FaqPage', 'placeDaysQuestion', 'Can we choose which days?'),
  ('en', 'FaqPage', 'placeHeading', 'Getting a place'),
  ('en', 'FaqPage', 'placeHoldAnswer', 'Yes, for up to two months, with the deposit paid. Longer than that and we would be holding an empty room a family on the list needs, so we would rather put you back near the top for the month you actually want.'),
  ('en', 'FaqPage', 'placeHoldQuestion', 'Can we hold a place for a later start?'),
  ('en', 'FaqPage', 'placeWaitlistAnswer', 'It is by room and by date you joined, not by who calls most. When a space comes up we work down the list and you get about a week to decide. Nobody moves up for paying more, and there is nothing to pay to be on it.'),
  ('en', 'FaqPage', 'placeWaitlistQuestion', 'How does the waiting list work?'),
  ('en', 'FaqPage', 'startingBringAnswer', 'A change of clothes, a coat that can get muddy, and whatever your child sleeps with. Not nappies, wipes, sunscreen, or food — those are in the rate, so nobody is scrambling at seven in the morning.'),
  ('en', 'FaqPage', 'startingBringQuestion', 'What do we need to bring?'),
  ('en', 'FaqPage', 'startingHeading', 'Starting here'),
  ('en', 'FaqPage', 'startingHearAnswer', 'Under threes get the day written down — every bottle, nap, and nappy — handed to you at pickup. Older children get it told to you at the door by the teacher who was actually with them, which is more use than a form.'),
  ('en', 'FaqPage', 'startingHearQuestion', 'How will we hear about our child''s day?'),
  ('en', 'FaqPage', 'startingSettleAnswer', 'Two short visits with you in the room before the start date, then a half day, then a full one. Some children skip straight to the full day and some need a fortnight, and neither is a problem — we follow your child rather than the plan.'),
  ('en', 'FaqPage', 'startingSettleQuestion', 'What does the first week look like?'),
  ('en', 'FaqPage', 'troubleBitingAnswer', 'Both sets of parents are told the same day, and neither child is named to the other family. Biting is normal in a toddler room and it is our job to shadow and redirect, not to ask a two-year-old to explain themselves.'),
  ('en', 'FaqPage', 'troubleBitingQuestion', 'What if our child bites, or is bitten?'),
  ('en', 'FaqPage', 'troubleComplaintAnswer', 'Tell Maria directly and you will get an answer within two days. If that does not settle it, the state licensing office takes complaints about us without going through us at all, and we will give you the number ourselves.'),
  ('en', 'FaqPage', 'troubleComplaintQuestion', 'How do we complain about you?'),
  ('en', 'FaqPage', 'troubleHeading', 'When something goes wrong'),
  ('en', 'FaqPage', 'troubleInjuryAnswer', 'Anything above a scraped knee gets a phone call while it is happening, not a note at pickup. Every injury is written up and you sign the record, including the ones that turned out to be nothing.'),
  ('en', 'FaqPage', 'troubleInjuryQuestion', 'What happens if our child is hurt?'),
  ('en', 'FaqPage', 'troubleSickAnswer', 'Fever, vomiting, or anything contagious means going home and staying home for twenty-four clear hours after it stops. It is genuinely inconvenient, and it is the reason the whole room is not unwell the following week.'),
  ('en', 'FaqPage', 'troubleSickQuestion', 'When is a child too unwell to come?'),
  ('en', 'FaqPage', 'visitBody', 'A list like this answers the questions we have already been asked. Yours may not be here, and the fastest way through it is standing in the building asking a person who can say “I do not know, let me find out” rather than picking from a page.'),
  ('en', 'FaqPage', 'visitHeading', 'Ask us the rest in person'),
  ('en', 'Footer', 'tagline', 'Licensed child care facility · State license {licenseNumber} · Serving families since {since}.'),
  ('en', 'HomePage', 'contactAddress', 'Address'),
  ('en', 'HomePage', 'contactHours', 'Hours'),
  ('en', 'HomePage', 'contactPhone', 'Phone'),
  ('en', 'HomePage', 'dayBody', 'Predictable rhythm, room to be a kid. Here is what nine hours actually looks like.'),
  ('en', 'HomePage', 'dayHeading', 'A day at Willow Grove'),
  ('en', 'HomePage', 'heroBody', 'A small, licensed center in {neighborhood}, where the same caregivers greet your child every morning and can tell you exactly how their day went.'),
  ('en', 'HomePage', 'heroEyebrow', 'Licensed child care · Ages {ageRange}'),
  ('en', 'HomePage', 'heroHeading', 'A place where your child is known by name.'),
  ('en', 'HomePage', 'infantsBlurb', 'One primary caregiver per child, so feeds, naps, and first words are tracked by someone who knows your baby — not whoever is free.'),
  ('en', 'HomePage', 'mapLabel', 'Map of {neighborhood}'),
  ('en', 'HomePage', 'metaDescription', 'A small, licensed child care center in Northwest Portland for ages 6 weeks to 5 years, where the same caregivers know your child by name. Call to plan a visit.'),
  ('en', 'HomePage', 'metaTitle', 'Willow Grove Children''s Center · Licensed child care in NW Portland'),
  ('en', 'HomePage', 'planVisit', 'Plan a visit'),
  ('en', 'HomePage', 'preschoolBlurb', 'Early literacy, numbers, and the harder work of taking turns and naming feelings — the groundwork for kindergarten.'),
  ('en', 'HomePage', 'programsHeading', 'Programs by age'),
  ('en', 'HomePage', 'staffHeading', 'The people who will know your child'),
  ('en', 'HomePage', 'testimonialAttribution', 'Priya R., parent of an infant-room child'),
  ('en', 'HomePage', 'testimonialHeading', 'From a parent'),
  ('en', 'HomePage', 'testimonialQuote', '“On day three, Aisha told me my daughter only settles for her nap if she can hold the blue elephant. I hadn''t told anyone that. That''s when I stopped worrying.”'),
  ('en', 'HomePage', 'toddlersBlurb', 'Room to move and language everywhere. Days are predictable so a toddler learning the world can count on what comes next.'),
  ('en', 'HomePage', 'trustInfantRatio', 'Infant ratio'),
  ('en', 'HomePage', 'trustOpenWeekdays', 'Open weekdays'),
  ('en', 'HomePage', 'trustStateLicense', 'State license'),
  ('en', 'HomePage', 'trustYearsCaring', 'Caring for families'),
  ('en', 'HomePage', 'visitHeading', 'Come see it for yourself'),
  ('en', 'HomePage', 'yearsValue', '{years} years'),
  ('en', 'Nav', 'about', 'About'),
  ('en', 'Nav', 'contact', 'Contact'),
  ('en', 'Nav', 'faq', 'FAQ'),
  ('en', 'Nav', 'home', 'Willow Grove home'),
  ('en', 'Nav', 'programs', 'Programs'),
  ('en', 'Nav', 'staff', 'Staff'),
  ('en', 'Nav', 'tuition', 'Tuition'),
  ('en', 'Programs', 'infants', 'Infants'),
  ('en', 'Programs', 'infantsAges', '6 weeks – 15 months'),
  ('en', 'Programs', 'infantsGroupSize', '8 children'),
  ('en', 'Programs', 'preschool', 'Preschool'),
  ('en', 'Programs', 'preschoolAges', '3 – 5 years'),
  ('en', 'Programs', 'preschoolGroupSize', '18 children'),
  ('en', 'Programs', 'toddlers', 'Toddlers'),
  ('en', 'Programs', 'toddlersAges', '15 months – 3 years'),
  ('en', 'Programs', 'toddlersGroupSize', '10 children'),
  ('en', 'ProgramsPage', 'dayBody', 'Every room runs on the same rhythm, scaled to the age. Infants sleep and eat on their own schedule inside it; older children move through it together.'),
  ('en', 'ProgramsPage', 'dayHeading', 'A day at Willow Grove'),
  ('en', 'ProgramsPage', 'eyebrow', 'Ages {ageRange}'),
  ('en', 'ProgramsPage', 'factAges', 'Ages'),
  ('en', 'ProgramsPage', 'factGroup', 'Group size'),
  ('en', 'ProgramsPage', 'factRatio', 'Ratio'),
  ('en', 'ProgramsPage', 'heading', 'Programs by age'),
  ('en', 'ProgramsPage', 'infantsDetail', 'Every baby is assigned one primary caregiver who handles their feeds, naps, and nappies. That is the person who learns that your daughter will only go down holding the blue elephant, and the person who tells you about it at pickup.'),
  ('en', 'ProgramsPage', 'infantsStaffing', 'Feeds and sleep follow your baby''s schedule, not the room''s. You get the day written down — every bottle, every nap, every nappy — before you reach the car park.'),
  ('en', 'ProgramsPage', 'intro', 'Three rooms in one building, and the same faces from the infant room to the morning your child leaves for kindergarten. Here is who is in each room, how many children they care for, and what the day holds.'),
  ('en', 'ProgramsPage', 'metaDescription', 'Infant, toddler, and preschool rooms in Northwest Portland — ratios, group sizes, and what a day actually looks like in each room.'),
  ('en', 'ProgramsPage', 'metaTitle', 'Programs'),
  ('en', 'ProgramsPage', 'preschoolDetail', 'Early literacy and numbers, and the harder curriculum underneath them — taking turns, waiting, saying what you feel instead of throwing something. This is the groundwork kindergarten expects a child to arrive with.'),
  ('en', 'ProgramsPage', 'preschoolStaffing', 'Small-group work every morning, led by a teacher who has taught this room for years. In the spring we write to your child''s kindergarten so their first teacher starts already knowing them.'),
  ('en', 'ProgramsPage', 'toddlersDetail', 'The year a child learns that the world has an order to it. Days are deliberately predictable, so a toddler who cannot yet tell time can still tell what comes next, and the language never stops — naming, narrating, asking.'),
  ('en', 'ProgramsPage', 'toddlersStaffing', 'Two teachers stay with this room all year. Toilet learning happens on your child''s timeline and in step with what you are doing at home, never on a deadline we set.'),
  ('en', 'ProgramsPage', 'visitAria', 'Plan a visit'),
  ('en', 'ProgramsPage', 'visitBody', 'Call the office and you will get a plain answer about which rooms have space and what the wait looks like for the ones that do not — then come and stand in the room your child would actually be in.'),
  ('en', 'ProgramsPage', 'visitHeading', 'Not sure which room fits?'),
  ('en', 'Staff', 'aishaBio', 'Eight years in the infant room and she has never once handed a parent a day sheet she had to guess at. She is the reason we can tell you which side your daughter prefers to be held on.'),
  ('en', 'Staff', 'aishaRole', 'Lead Infant Teacher'),
  ('en', 'Staff', 'danielBio', 'Spends his day narrating the world to people who have just discovered it has words. Toilet learning happens on his watch, on your child''s timeline, and he will never make you feel behind.'),
  ('en', 'Staff', 'danielRole', 'Lead Toddler Teacher'),
  ('en', 'Staff', 'graceBio', 'Came to us from a hospital nursery, which shows in how she handles a baby who will not settle. She has the calmest hands in the building and the room is quieter for it.'),
  ('en', 'Staff', 'graceRole', 'Infant Teacher'),
  ('en', 'Staff', 'mariaBio', 'Runs the place, and still covers the infant room when someone is off sick. She is the one you will be handed to when you call, and the one who will tell you plainly if the room you want has a nine-month wait.'),
  ('en', 'Staff', 'mariaRole', 'Director'),
  ('en', 'Staff', 'nadiaBio', 'Handles enrolment, the waiting list, and every piece of paper the state asks for. If you have ever been given a vague answer about fees somewhere else, she is the correction to that.'),
  ('en', 'Staff', 'nadiaRole', 'Assistant Director'),
  ('en', 'Staff', 'sofiaBio', 'Cooks every meal on site, which is why we can be exact about allergies rather than hopeful. She knows which children will eat a vegetable only if it is cut a particular way, and cuts it that way.'),
  ('en', 'Staff', 'sofiaRole', 'Cook'),
  ('en', 'Staff', 'tenure', 'with Willow Grove {years} years'),
  ('en', 'Staff', 'tomBio', 'Teaches the small-group work every morning and writes to each child''s kindergarten in the spring, so their first teacher starts already knowing them. Six years in the same room.'),
  ('en', 'Staff', 'tomRole', 'Lead Preschool Teacher'),
  ('en', 'StaffPage', 'eyebrow', '{count} teachers and staff'),
  ('en', 'StaffPage', 'factChecksLabel', 'Every hire'),
  ('en', 'StaffPage', 'factChecksValue', 'Background-checked, CPR and first aid current'),
  ('en', 'StaffPage', 'factLongestLabel', 'Longest with us'),
  ('en', 'StaffPage', 'factTeamLabel', 'Teachers and staff'),
  ('en', 'StaffPage', 'factTenureLabel', 'Average time with us'),
  ('en', 'StaffPage', 'heading', 'The people who will know your child'),
  ('en', 'StaffPage', 'intro', 'The tour tells you about the building. This page tells you about the people in it, because a room is only as steady as whoever is standing in it — and how long they have stayed is the one thing a brochure cannot fake.'),
  ('en', 'StaffPage', 'metaDescription', 'The teachers and staff at a licensed child care center in Northwest Portland — who they are, how long they have been here, and why that is the number to compare.'),
  ('en', 'StaffPage', 'metaTitle', 'Staff'),
  ('en', 'StaffPage', 'stayBody', 'Turnover is the thing that quietly wrecks a center, and it is almost never mentioned on a website. Here is what we do about it, so you can ask the next center you visit the same three questions.'),
  ('en', 'StaffPage', 'stayHeading', 'Why people stay'),
  ('en', 'StaffPage', 'stayHiringBody', 'A vacancy is covered by the director and the assistant director rather than filled quickly. Every hire is background-checked before their first day with children, with no exceptions for busy weeks.'),
  ('en', 'StaffPage', 'stayHiringTitle', 'Slow to hire, on purpose'),
  ('en', 'StaffPage', 'stayPayBody', 'Teachers are paid above what centers around us pay, and the pay rises with time here rather than with a job title. It is the largest thing on our cost sheet and the reason tuition is what it is.'),
  ('en', 'StaffPage', 'stayPayTitle', 'Paid above the going rate, deliberately'),
  ('en', 'StaffPage', 'stayRoomBody', 'Nobody is moved between rooms to plug a gap. A teacher stays with their group for the year, which is what makes a primary caregiver mean anything beyond a word on a page.'),
  ('en', 'StaffPage', 'stayRoomTitle', 'The same room, all year'),
  ('en', 'StaffPage', 'teamBody', 'Portraits are coming; the initials are a placeholder, not a stock photo of somebody else''s staff. Everything under each name is true of the person who will actually be in the room.'),
  ('en', 'StaffPage', 'teamHeading', 'Who is here'),
  ('en', 'StaffPage', 'visitBody', 'Names on a page are not much use. Come and watch the room your child would be in, and see whether the person in it looks like someone your child would settle with.'),
  ('en', 'StaffPage', 'visitHeading', 'Come and meet them'),
  ('en', 'StaffPage', 'yearsValue', '{years} years'),
  ('en', 'TuitionPage', 'eyebrow', 'From {lowest} a month, full time'),
  ('en', 'TuitionPage', 'factDepositLabel', 'Deposit'),
  ('en', 'TuitionPage', 'factDepositValue', '{weeks} weeks, refundable when you leave'),
  ('en', 'TuitionPage', 'factIncludedLabel', 'Included in the rate'),
  ('en', 'TuitionPage', 'factIncludedValue', 'Meals, snacks, nappies, wipes, and sunscreen'),
  ('en', 'TuitionPage', 'factNoticeLabel', 'Notice to leave'),
  ('en', 'TuitionPage', 'factNoticeValue', '{weeks} weeks, in writing'),
  ('en', 'TuitionPage', 'factRegistrationLabel', 'Registration'),
  ('en', 'TuitionPage', 'factRegistrationValue', '{amount}, once, at enrolment'),
  ('en', 'TuitionPage', 'fiveDayBody', 'The full week, and the only schedule where your child has the same group around them every day. It is what we recommend for infants, who settle faster when the week does not keep changing shape.'),
  ('en', 'TuitionPage', 'fiveDayDays', 'Monday to Friday'),
  ('en', 'TuitionPage', 'fiveDayName', 'Five days'),
  ('en', 'TuitionPage', 'heading', 'What a place here costs'),
  ('en', 'TuitionPage', 'hiddenBody', 'None of this is buried in a contract you sign on the last day. It is here, before you call, because the cost of child care is not only the number in the table.'),
  ('en', 'TuitionPage', 'hiddenClosuresBody', 'Public holidays, plus three staff training days a year and the week between Christmas and New Year. Those are charged — the rate is monthly, not per day attended — and the dates are published each August, a year ahead.'),
  ('en', 'TuitionPage', 'hiddenClosuresTitle', 'Days we are closed'),
  ('en', 'TuitionPage', 'hiddenHeading', 'The parts a rate sheet usually leaves out'),
  ('en', 'TuitionPage', 'hiddenHelpBody', 'We accept state subsidy and take dependent-care benefits from employers. Nadia handles both, and she will tell you what you are likely to qualify for before you fill in anything — including when the answer is nothing.'),
  ('en', 'TuitionPage', 'hiddenHelpTitle', 'Help with the cost'),
  ('en', 'TuitionPage', 'hiddenIncreaseBody', 'Rates go up once a year and it is usually a few per cent, tracking what we pay teachers. You get it in writing in June for a September start, so nobody is surprised by an invoice.'),
  ('en', 'TuitionPage', 'hiddenIncreaseTitle', 'The annual increase'),
  ('en', 'TuitionPage', 'hiddenLateBody', '{amount} a minute after six, charged in whole minutes and added to the next invoice. It is not a punishment; it is what it costs to keep two members of staff in the building, and two is the minimum the license allows.'),
  ('en', 'TuitionPage', 'hiddenLateTitle', 'Late pickup'),
  ('en', 'TuitionPage', 'hiddenSiblingBody', '{percent}% off the younger child''s rate, applied automatically for as long as both are enrolled. You do not have to ask for it, and nobody has to remember to add it.'),
  ('en', 'TuitionPage', 'hiddenSiblingTitle', 'Two children here'),
  ('en', 'TuitionPage', 'intro', 'Most centers make you call for this. We would rather you saw the number now and decided whether it is worth a phone call, than found out at the end of a tour you spent a morning on. Every rate we charge is on this page.'),
  ('en', 'TuitionPage', 'metaDescription', 'What child care actually costs in Northwest Portland — monthly rates for every room and schedule, published on the page, plus the fees a rate sheet usually leaves out.'),
  ('en', 'TuitionPage', 'metaTitle', 'Tuition'),
  ('en', 'TuitionPage', 'ratesBody', 'Rates are monthly and do not change with the length of the month — you pay the same in February as in March. A part-time place costs more per day than a full-time one, because the room is staffed for the whole week whether or not your child is in it that day.'),
  ('en', 'TuitionPage', 'ratesFootnote', 'Rates are reviewed once a year, in September, and we tell you in writing by the preceding June — never mid-year, and never with less than a term''s warning.'),
  ('en', 'TuitionPage', 'ratesHeading', 'Monthly rates'),
  ('en', 'TuitionPage', 'ratesRoom', 'Room'),
  ('en', 'TuitionPage', 'ratesTableCaption', 'Monthly tuition by room and schedule'),
  ('en', 'TuitionPage', 'schedulesBody', 'Three schedules, on fixed days. You can move between them when a place opens in the one you want, and you keep your spot on the list while you wait.'),
  ('en', 'TuitionPage', 'schedulesHeading', 'Schedule options'),
  ('en', 'TuitionPage', 'schedulesSwitching', 'Changing schedule needs a month''s notice and a place in the room on the days you are moving to. We will tell you honestly whether that is weeks away or most of a year.'),
  ('en', 'TuitionPage', 'threeDayBody', 'Fixed days rather than days you pick each week, so your child knows which mornings are theirs and the room can hold a consistent group. Most families on this schedule are splitting the week with a grandparent.'),
  ('en', 'TuitionPage', 'threeDayDays', 'Monday, Wednesday, Friday'),
  ('en', 'TuitionPage', 'threeDayName', 'Three days'),
  ('en', 'TuitionPage', 'twoDayBody', 'Enough to keep a routine and a friendship going without a full week. Places on this schedule are the scarcest we have, because two of them fill one full-time space and both have to line up.'),
  ('en', 'TuitionPage', 'twoDayDays', 'Tuesday and Thursday'),
  ('en', 'TuitionPage', 'twoDayName', 'Two days'),
  ('en', 'TuitionPage', 'visitBody', 'You have the numbers, which is most of what a tour would have told you about money. What is left is whether the room is worth it, and that is the one thing a rate sheet cannot show you.'),
  ('en', 'TuitionPage', 'visitHeading', 'Worth a call before you decide'),
  ('en', 'Visit', 'askLabel', 'Ask for'),
  ('en', 'Visit', 'askValue', 'Maria, the director'),
  ('en', 'Visit', 'bookingLabel', 'Booking'),
  ('en', 'Visit', 'bookingValue', 'No appointment needed'),
  ('en', 'Visit', 'call', 'Call'),
  ('en', 'Visit', 'cardHeading', 'What a visit looks like'),
  ('en', 'Visit', 'lengthLabel', 'How long it takes'),
  ('en', 'Visit', 'lengthValue', 'About twenty minutes'),
  ('en', 'Visit', 'whenLabel', 'Best time to come'),
  ('en', 'Visit', 'whenValue', 'Ten in the morning, while the rooms are running')
) as v (locale, namespace, key, value)
where o.slug = 'willow-grove'
on conflict (org_id, locale, namespace, key) where status = 'published'
do update set value = excluded.value;
