-- Backfill: the English catalogue becomes rows in public.prose.
--
-- GENERATED FILE — do not edit by hand.
--   node scripts/generate-prose-backfill.mjs          regenerates it
--   node scripts/generate-prose-backfill.mjs --check  fails if this file drifted
--
-- ---------------------------------------------------------------------------------------
-- WHAT THIS MOVES
-- ---------------------------------------------------------------------------------------
--
-- 279 strings, every one of them from messages/en.json, copied verbatim. The three that
-- stay behind are UI chrome — Nav.label, Nav.openMenu, Nav.closeMenu — which describe the
-- navigation rather than the center. scripts/generate-prose-backfill.mjs holds that boundary
-- as a list and explains it.
--
-- Rows are inserted as 'published', not 'draft'. These strings are on the live site right
-- now; landing them as drafts would mean the first build after this migration finds no
-- published prose and fails, and someone would have to press Publish to restore copy that
-- was never unpublished.
--
-- ---------------------------------------------------------------------------------------
-- SAFE TO RUN TWICE
-- ---------------------------------------------------------------------------------------
--
-- The upsert targets prose_one_published_per_key, the partial unique index from the table's
-- own migration. A second run updates the same rows in place. It does NOT touch drafts: a
-- staff member's unpublished edit survives a re-run, because the index this conflicts on is
-- scoped to published rows.
--
-- It never deletes, for the reason supabase/README.md gives about the seed — a backfill that
-- removed whatever it did not recognise would be one careless edit away from destroying copy
-- the editor wrote.

insert into public.prose (org_id, locale, namespace, key, value, status)
select o.id, 'en', v.namespace, v.key, v.value, 'published'
from public.orgs o
cross join (values
  ('Nav', 'home', 'Willow Grove home'),
  ('Nav', 'programs', 'Programs'),
  ('Nav', 'about', 'About'),
  ('Nav', 'staff', 'Staff'),
  ('Nav', 'tuition', 'Tuition'),
  ('Nav', 'faq', 'FAQ'),
  ('Nav', 'contact', 'Contact'),
  ('Programs', 'infants', 'Infants'),
  ('Programs', 'toddlers', 'Toddlers'),
  ('Programs', 'preschool', 'Preschool'),
  ('Staff', 'tenure', 'with Willow Grove {years} years'),
  ('Staff', 'mariaRole', 'Director'),
  ('Staff', 'mariaBio', 'Runs the place, and still covers the infant room when someone is off sick. She is the one you will be handed to when you call, and the one who will tell you plainly if the room you want has a nine-month wait.'),
  ('Staff', 'nadiaRole', 'Assistant Director'),
  ('Staff', 'nadiaBio', 'Handles enrolment, the waiting list, and every piece of paper the state asks for. If you have ever been given a vague answer about fees somewhere else, she is the correction to that.'),
  ('Staff', 'aishaRole', 'Lead Infant Teacher'),
  ('Staff', 'aishaBio', 'Eight years in the infant room and she has never once handed a parent a day sheet she had to guess at. She is the reason we can tell you which side your daughter prefers to be held on.'),
  ('Staff', 'graceRole', 'Infant Teacher'),
  ('Staff', 'graceBio', 'Came to us from a hospital nursery, which shows in how she handles a baby who will not settle. She has the calmest hands in the building and the room is quieter for it.'),
  ('Staff', 'danielRole', 'Lead Toddler Teacher'),
  ('Staff', 'danielBio', 'Spends his day narrating the world to people who have just discovered it has words. Toilet learning happens on his watch, on your child''s timeline, and he will never make you feel behind.'),
  ('Staff', 'tomRole', 'Lead Preschool Teacher'),
  ('Staff', 'tomBio', 'Teaches the small-group work every morning and writes to each child''s kindergarten in the spring, so their first teacher starts already knowing them. Six years in the same room.'),
  ('Staff', 'sofiaRole', 'Cook'),
  ('Staff', 'sofiaBio', 'Cooks every meal on site, which is why we can be exact about allergies rather than hopeful. She knows which children will eat a vegetable only if it is cut a particular way, and cuts it that way.'),
  ('StaffPage', 'metaTitle', 'Staff'),
  ('StaffPage', 'metaDescription', 'The teachers and staff at a licensed child care center in Northwest Portland — who they are, how long they have been here, and why that is the number to compare.'),
  ('StaffPage', 'eyebrow', '{count} teachers and staff'),
  ('StaffPage', 'heading', 'The people who will know your child'),
  ('StaffPage', 'intro', 'The tour tells you about the building. This page tells you about the people in it, because a room is only as steady as whoever is standing in it — and how long they have stayed is the one thing a brochure cannot fake.'),
  ('StaffPage', 'factTeamLabel', 'Teachers and staff'),
  ('StaffPage', 'factTenureLabel', 'Average time with us'),
  ('StaffPage', 'factLongestLabel', 'Longest with us'),
  ('StaffPage', 'factChecksLabel', 'Every hire'),
  ('StaffPage', 'factChecksValue', 'Background-checked, CPR and first aid current'),
  ('StaffPage', 'yearsValue', '{years} years'),
  ('StaffPage', 'teamHeading', 'Who is here'),
  ('StaffPage', 'teamBody', 'Portraits are coming; the initials are a placeholder, not a stock photo of somebody else''s staff. Everything under each name is true of the person who will actually be in the room.'),
  ('StaffPage', 'stayHeading', 'Why people stay'),
  ('StaffPage', 'stayBody', 'Turnover is the thing that quietly wrecks a center, and it is almost never mentioned on a website. Here is what we do about it, so you can ask the next center you visit the same three questions.'),
  ('StaffPage', 'stayPayTitle', 'Paid above the going rate, deliberately'),
  ('StaffPage', 'stayPayBody', 'Teachers are paid above what centers around us pay, and the pay rises with time here rather than with a job title. It is the largest thing on our cost sheet and the reason tuition is what it is.'),
  ('StaffPage', 'stayRoomTitle', 'The same room, all year'),
  ('StaffPage', 'stayRoomBody', 'Nobody is moved between rooms to plug a gap. A teacher stays with their group for the year, which is what makes a primary caregiver mean anything beyond a word on a page.'),
  ('StaffPage', 'stayHiringTitle', 'Slow to hire, on purpose'),
  ('StaffPage', 'stayHiringBody', 'A vacancy is covered by the director and the assistant director rather than filled quickly. Every hire is background-checked before their first day with children, with no exceptions for busy weeks.'),
  ('StaffPage', 'visitHeading', 'Come and meet them'),
  ('StaffPage', 'visitBody', 'Names on a page are not much use. Come and watch the room your child would be in, and see whether the person in it looks like someone your child would settle with.'),
  ('Day', 'arrival', 'Arrival and free play'),
  ('Day', 'breakfast', 'Breakfast, then morning circle'),
  ('Day', 'centers', 'Learning centers and outdoor time'),
  ('Day', 'lunch', 'Lunch, made on site'),
  ('Day', 'nap', 'Nap and quiet rest'),
  ('Day', 'snack', 'Snack and afternoon projects'),
  ('Day', 'pickup', 'Outdoor play until pickup'),
  ('Visit', 'cardHeading', 'What a visit looks like'),
  ('Visit', 'whenLabel', 'Best time to come'),
  ('Visit', 'whenValue', 'Ten in the morning, while the rooms are running'),
  ('Visit', 'askLabel', 'Ask for'),
  ('Visit', 'askValue', 'Maria, the director'),
  ('Visit', 'lengthLabel', 'How long it takes'),
  ('Visit', 'lengthValue', 'About twenty minutes'),
  ('Visit', 'bookingLabel', 'Booking'),
  ('Visit', 'bookingValue', 'No appointment needed'),
  ('ProgramsPage', 'metaTitle', 'Programs'),
  ('ProgramsPage', 'metaDescription', 'Infant, toddler, and preschool rooms in Northwest Portland — ratios, group sizes, and what a day actually looks like in each room.'),
  ('ProgramsPage', 'eyebrow', 'Ages {ageRange}'),
  ('ProgramsPage', 'heading', 'Programs by age'),
  ('ProgramsPage', 'intro', 'Three rooms in one building, and the same faces from the infant room to the morning your child leaves for kindergarten. Here is who is in each room, how many children they care for, and what the day holds.'),
  ('ProgramsPage', 'factRatio', 'Ratio'),
  ('ProgramsPage', 'factGroup', 'Group size'),
  ('ProgramsPage', 'factAges', 'Ages'),
  ('ProgramsPage', 'infantsDetail', 'Every baby is assigned one primary caregiver who handles their feeds, naps, and nappies. That is the person who learns that your daughter will only go down holding the blue elephant, and the person who tells you about it at pickup.'),
  ('ProgramsPage', 'infantsStaffing', 'Feeds and sleep follow your baby''s schedule, not the room''s. You get the day written down — every bottle, every nap, every nappy — before you reach the car park.'),
  ('ProgramsPage', 'toddlersDetail', 'The year a child learns that the world has an order to it. Days are deliberately predictable, so a toddler who cannot yet tell time can still tell what comes next, and the language never stops — naming, narrating, asking.'),
  ('ProgramsPage', 'toddlersStaffing', 'Two teachers stay with this room all year. Toilet learning happens on your child''s timeline and in step with what you are doing at home, never on a deadline we set.'),
  ('ProgramsPage', 'preschoolDetail', 'Early literacy and numbers, and the harder curriculum underneath them — taking turns, waiting, saying what you feel instead of throwing something. This is the groundwork kindergarten expects a child to arrive with.'),
  ('ProgramsPage', 'preschoolStaffing', 'Small-group work every morning, led by a teacher who has taught this room for years. In the spring we write to your child''s kindergarten so their first teacher starts already knowing them.'),
  ('ProgramsPage', 'dayHeading', 'A day at Willow Grove'),
  ('ProgramsPage', 'dayBody', 'Every room runs on the same rhythm, scaled to the age. Infants sleep and eat on their own schedule inside it; older children move through it together.'),
  ('ProgramsPage', 'visitHeading', 'Not sure which room fits?'),
  ('ProgramsPage', 'visitBody', 'Call the office and you will get a plain answer about which rooms have space and what the wait looks like for the ones that do not — then come and stand in the room your child would actually be in.'),
  ('ProgramsPage', 'visitAria', 'Plan a visit'),
  ('AboutPage', 'metaTitle', 'About'),
  ('AboutPage', 'metaDescription', 'A licensed child care center in Northwest Portland since {since} — our approach, our ratios, our state license, and what safety looks like on an ordinary day.'),
  ('AboutPage', 'eyebrow', 'Licensed since {since}'),
  ('AboutPage', 'heading', 'How we care for children, and why'),
  ('AboutPage', 'intro', 'A center is easy to describe well and hard to run well. This page is the second thing — how the rooms are staffed, what the license behind the front door actually covers, and what happens on the ordinary days nobody writes a brochure about.'),
  ('AboutPage', 'philosophyHeading', 'What we believe'),
  ('AboutPage', 'philosophyKnownTitle', 'A child should be known by a few people, not minded by many'),
  ('AboutPage', 'philosophyKnownBody', 'Every child has a primary caregiver, and teachers stay with their room for the year. It is why we can tell you at pickup that your son ate half his lunch and then fell asleep on the reading cushion — someone was there for all of it.'),
  ('AboutPage', 'philosophyRhythmTitle', 'The day should be predictable, the play should not'),
  ('AboutPage', 'philosophyRhythmBody', 'The same rhythm every day — arrival, breakfast, circle, outside, lunch, rest. A child who knows what comes next has the confidence to be inventive inside it. Structure is what makes the mess possible.'),
  ('AboutPage', 'philosophyPlainTitle', 'Parents get the truth, including the parts that are hard'),
  ('AboutPage', 'philosophyPlainBody', 'If your child bit someone, we will tell you. If a room is full and the wait is nine months, we will say nine months rather than let you hope. You cannot leave your child somewhere you have caught being vague.'),
  ('AboutPage', 'ratiosHeading', 'Ratios and group sizes'),
  ('AboutPage', 'ratiosBody', 'These are the numbers we staff to every hour we are open, not an average across the week. Both matter: the ratio is how much attention your child gets, and the group size is how loud and how busy the room is around them.'),
  ('AboutPage', 'ratiosTableCaption', 'Staffing ratio and group size by room'),
  ('AboutPage', 'ratiosRoom', 'Room'),
  ('AboutPage', 'ratiosAges', 'Ages'),
  ('AboutPage', 'ratiosRatio', 'Ratio'),
  ('AboutPage', 'ratiosGroup', 'Group size'),
  ('AboutPage', 'ratiosFootnote', 'Our ratios are at or below what the state requires for each age, and we hold them through nap, lunch, and the end of the day — the hours a ratio is easiest to quietly let slip.'),
  ('AboutPage', 'licensingHeading', 'Licensing and the checks behind it'),
  ('AboutPage', 'licensingBody', 'We have held a state child care license continuously since {since}. A license is not a certificate on a wall; it is an inspection regime, and we would rather you know exactly what it covers before you ask.'),
  ('AboutPage', 'licensingNumberLabel', 'State license'),
  ('AboutPage', 'licensingSinceLabel', 'Licensed since'),
  ('AboutPage', 'licensingInspectionsLabel', 'Inspections'),
  ('AboutPage', 'licensingInspectionsValue', 'Unannounced, at least annually'),
  ('AboutPage', 'licensingStaffLine', 'Every member of staff is background-checked before their first day with children, and holds current CPR and first aid certification — the director included.'),
  ('AboutPage', 'licensingCoversHeading', 'What an inspection covers'),
  ('AboutPage', 'licensingCoversRatios', 'Ratios and supervision, room by room'),
  ('AboutPage', 'licensingCoversKitchen', 'The kitchen, food handling, and allergy practice'),
  ('AboutPage', 'licensingCoversSleep', 'Safe sleep, cots, and nap routines'),
  ('AboutPage', 'licensingCoversBuilding', 'Building, playground, exits, and drills'),
  ('AboutPage', 'licensingCoversRecords', 'Staff files, clearances, and training records'),
  ('AboutPage', 'licensingRecords', 'The state keeps our full inspection history, and you are entitled to read it. Ask at the office and we will show you ours, findings included.'),
  ('AboutPage', 'safetyHeading', 'Safety, on an ordinary day'),
  ('AboutPage', 'safetyBody', 'Most of safety is not dramatic. It is the same small routines done the same way every day, by people who are not improvising.'),
  ('AboutPage', 'safetyEntryTitle', 'One locked door'),
  ('AboutPage', 'safetyEntryBody', 'A single entrance with a keypad code, changed each term. Nobody who is not on your child''s authorized list leaves with them — no exceptions made at the door, ever, however plausible the person seems.'),
  ('AboutPage', 'safetySignInTitle', 'Signed in and counted'),
  ('AboutPage', 'safetySignInBody', 'Every child is signed in and out by name, and teachers count their group at every transition — into the room, out to the yard, back from the yard.'),
  ('AboutPage', 'safetyAllergyTitle', 'Allergies and medication'),
  ('AboutPage', 'safetyAllergyBody', 'Allergies are posted in the room and in the kitchen, meals are made on site so we control what is in them, and medication is given only with your written instruction and logged when it is.'),
  ('AboutPage', 'safetyIllnessTitle', 'Illness, said plainly'),
  ('AboutPage', 'safetyIllnessBody', 'Fever, vomiting, or anything contagious means going home and staying home for twenty-four clear hours. It is inconvenient, and it is the reason the whole room is not sick next week.'),
  ('AboutPage', 'safetyDrillsTitle', 'Practised, not planned'),
  ('AboutPage', 'safetyDrillsBody', 'Fire drills monthly and emergency procedures quarterly, with the children, so the routine is familiar to them rather than frightening.'),
  ('AboutPage', 'visitHeading', 'The part that matters is standing in the room'),
  ('AboutPage', 'visitBody', 'None of this is worth much on a screen. Every center looks calm at nap time; what you want to see is a room with children awake in it, and the only way to see that is to be standing in one.'),
  ('AboutPage', 'visitAria', 'Plan a visit'),
  ('TuitionPage', 'metaTitle', 'Tuition'),
  ('TuitionPage', 'metaDescription', 'What child care actually costs in Northwest Portland — monthly rates for every room and schedule, published on the page, plus the fees a rate sheet usually leaves out.'),
  ('TuitionPage', 'eyebrow', 'From {lowest} a month, full time'),
  ('TuitionPage', 'heading', 'What a place here costs'),
  ('TuitionPage', 'intro', 'Most centers make you call for this. We would rather you saw the number now and decided whether it is worth a phone call, than found out at the end of a tour you spent a morning on. Every rate we charge is on this page.'),
  ('TuitionPage', 'factRegistrationLabel', 'Registration'),
  ('TuitionPage', 'factRegistrationValue', '{amount}, once, at enrolment'),
  ('TuitionPage', 'factDepositLabel', 'Deposit'),
  ('TuitionPage', 'factDepositValue', '{weeks} weeks, refundable when you leave'),
  ('TuitionPage', 'factIncludedLabel', 'Included in the rate'),
  ('TuitionPage', 'factIncludedValue', 'Meals, snacks, nappies, wipes, and sunscreen'),
  ('TuitionPage', 'factNoticeLabel', 'Notice to leave'),
  ('TuitionPage', 'factNoticeValue', '{weeks} weeks, in writing'),
  ('TuitionPage', 'ratesHeading', 'Monthly rates'),
  ('TuitionPage', 'ratesBody', 'Rates are monthly and do not change with the length of the month — you pay the same in February as in March. A part-time place costs more per day than a full-time one, because the room is staffed for the whole week whether or not your child is in it that day.'),
  ('TuitionPage', 'ratesTableCaption', 'Monthly tuition by room and schedule'),
  ('TuitionPage', 'ratesRoom', 'Room'),
  ('TuitionPage', 'ratesFootnote', 'Rates are reviewed once a year, in September, and we tell you in writing by the preceding June — never mid-year, and never with less than a term''s warning.'),
  ('TuitionPage', 'fiveDayName', 'Five days'),
  ('TuitionPage', 'fiveDayDays', 'Monday to Friday'),
  ('TuitionPage', 'fiveDayBody', 'The full week, and the only schedule where your child has the same group around them every day. It is what we recommend for infants, who settle faster when the week does not keep changing shape.'),
  ('TuitionPage', 'threeDayName', 'Three days'),
  ('TuitionPage', 'threeDayDays', 'Monday, Wednesday, Friday'),
  ('TuitionPage', 'threeDayBody', 'Fixed days rather than days you pick each week, so your child knows which mornings are theirs and the room can hold a consistent group. Most families on this schedule are splitting the week with a grandparent.'),
  ('TuitionPage', 'twoDayName', 'Two days'),
  ('TuitionPage', 'twoDayDays', 'Tuesday and Thursday'),
  ('TuitionPage', 'twoDayBody', 'Enough to keep a routine and a friendship going without a full week. Places on this schedule are the scarcest we have, because two of them fill one full-time space and both have to line up.'),
  ('TuitionPage', 'schedulesHeading', 'Schedule options'),
  ('TuitionPage', 'schedulesBody', 'Three schedules, on fixed days. You can move between them when a place opens in the one you want, and you keep your spot on the list while you wait.'),
  ('TuitionPage', 'schedulesSwitching', 'Changing schedule needs a month''s notice and a place in the room on the days you are moving to. We will tell you honestly whether that is weeks away or most of a year.'),
  ('TuitionPage', 'hiddenHeading', 'The parts a rate sheet usually leaves out'),
  ('TuitionPage', 'hiddenBody', 'None of this is buried in a contract you sign on the last day. It is here, before you call, because the cost of child care is not only the number in the table.'),
  ('TuitionPage', 'hiddenLateTitle', 'Late pickup'),
  ('TuitionPage', 'hiddenLateBody', '{amount} a minute after six, charged in whole minutes and added to the next invoice. It is not a punishment; it is what it costs to keep two members of staff in the building, and two is the minimum the license allows.'),
  ('TuitionPage', 'hiddenClosuresTitle', 'Days we are closed'),
  ('TuitionPage', 'hiddenClosuresBody', 'Public holidays, plus three staff training days a year and the week between Christmas and New Year. Those are charged — the rate is monthly, not per day attended — and the dates are published each August, a year ahead.'),
  ('TuitionPage', 'hiddenIncreaseTitle', 'The annual increase'),
  ('TuitionPage', 'hiddenIncreaseBody', 'Rates go up once a year and it is usually a few per cent, tracking what we pay teachers. You get it in writing in June for a September start, so nobody is surprised by an invoice.'),
  ('TuitionPage', 'hiddenSiblingTitle', 'Two children here'),
  ('TuitionPage', 'hiddenSiblingBody', '{percent}% off the younger child''s rate, applied automatically for as long as both are enrolled. You do not have to ask for it, and nobody has to remember to add it.'),
  ('TuitionPage', 'hiddenHelpTitle', 'Help with the cost'),
  ('TuitionPage', 'hiddenHelpBody', 'We accept state subsidy and take dependent-care benefits from employers. Nadia handles both, and she will tell you what you are likely to qualify for before you fill in anything — including when the answer is nothing.'),
  ('TuitionPage', 'visitHeading', 'Worth a call before you decide'),
  ('TuitionPage', 'visitBody', 'You have the numbers, which is most of what a tour would have told you about money. What is left is whether the room is worth it, and that is the one thing a rate sheet cannot show you.'),
  ('ContactPage', 'metaTitle', 'Contact'),
  ('ContactPage', 'metaDescription', 'Call, email, or visit a licensed child care center in Northwest Portland — phone, address, opening hours, parking, and how to get here by bus, bike, or on foot.'),
  ('ContactPage', 'eyebrow', 'One number, one address'),
  ('ContactPage', 'heading', 'Call us, or come and stand in the room'),
  ('ContactPage', 'intro', 'The phone is answered by someone who works here, not a service, and you will get a plain answer about space and waiting lists on the first call. Everything you need to reach us or find us is on this page.'),
  ('ContactPage', 'factAddressLabel', 'Address'),
  ('ContactPage', 'factHoursLabel', 'Open'),
  ('ContactPage', 'factClosedLabel', 'Closed'),
  ('ContactPage', 'factClosedValue', 'Weekends and public holidays'),
  ('ContactPage', 'factEmailLabel', 'Email'),
  ('ContactPage', 'gettingHereHeading', 'Getting here'),
  ('ContactPage', 'gettingHereBody', 'We are on a residential block, which is lovely at eight in the morning and awkward if you are circling for a space. Here is what the school run actually looks like, so your first drop-off is not also your first time working it out.'),
  ('ContactPage', 'drivingTitle', 'Driving and parking'),
  ('ContactPage', 'drivingBody', 'Four marked spaces beside the building are reserved for drop-off and pickup, fifteen minutes each. Street parking on the block is unrestricted, and the far end is usually open even at half past eight.'),
  ('ContactPage', 'transitTitle', 'By bus or streetcar'),
  ('ContactPage', 'transitBody', 'The nearest bus stop is a three-minute walk, and the streetcar line is about eight minutes on foot. Both leave you on the park side of the street, so you cross once and away from traffic.'),
  ('ContactPage', 'footTitle', 'On foot and by bike'),
  ('ContactPage', 'footBody', 'One block from Wallace Park, with a covered bike rack inside the gate. Buggies and strollers go in the entry hall rather than the rooms — there is space for them, and it keeps the doorways clear.'),
  ('ContactPage', 'mapLabel', 'Map placeholder — {address}'),
  ('ContactPage', 'callHeading', 'What to call about, and who you will get'),
  ('ContactPage', 'callBody', 'One number reaches all of it. Saying which of these it is when someone picks up gets you to the right person faster.'),
  ('ContactPage', 'callPlaceTitle', 'A place for your child'),
  ('ContactPage', 'callPlaceBody', 'Ask for Nadia, who keeps the waiting list. She will tell you which rooms have space and, if the one you want does not, how long the wait honestly is — including when the answer is most of a year.'),
  ('ContactPage', 'callIllnessTitle', 'Your child is unwell today'),
  ('ContactPage', 'callIllnessBody', 'Call before nine so the room can plan its morning. Tell us the symptom rather than the diagnosis; whether it is a twenty-four-hour exclusion is our job to work out, not yours.'),
  ('ContactPage', 'callHoursTitle', 'Outside opening hours'),
  ('ContactPage', 'callHoursBody', 'Voicemail after six, picked up when the office opens at seven the next morning. Nothing is answered overnight, so if it cannot wait until then, it should not be a message.'),
  ('ContactPage', 'emailNote', 'Email is read once a day, in the afternoon. For anything about a place, a start date, or a child who is unwell, please call — you will get an answer in the same conversation rather than tomorrow.'),
  ('ContactPage', 'visitHeading', 'The visit is the part that decides it'),
  ('ContactPage', 'visitBody', 'You have the number and you know where we are. What is left is the part no page can do for you: standing in a room on an ordinary morning and deciding whether these are the people you want holding your child.'),
  ('FaqPage', 'metaTitle', 'FAQ'),
  ('FaqPage', 'metaDescription', 'The questions parents actually ask a licensed child care center in Northwest Portland — waiting lists, settling in, food and allergies, illness, and what happens when something goes wrong.'),
  ('FaqPage', 'eyebrow', '{count} questions, answered'),
  ('FaqPage', 'heading', 'The questions parents actually ask'),
  ('FaqPage', 'intro', 'These are taken from the phone, not invented for a website. They include the awkward ones — what happens when a child bites, how to complain about us — because those are the ones you cannot ask on a tour without feeling rude, and they are the ones worth knowing the answer to.'),
  ('FaqPage', 'factAgesLabel', 'Ages we take'),
  ('FaqPage', 'factCountLabel', 'Questions answered here'),
  ('FaqPage', 'factSourceLabel', 'Where these came from'),
  ('FaqPage', 'factSourceValue', 'The office phone, over about a year'),
  ('FaqPage', 'factMissingLabel', 'Not on this list'),
  ('FaqPage', 'factMissingValue', 'Call and ask — it gets added'),
  ('FaqPage', 'placeHeading', 'Getting a place'),
  ('FaqPage', 'placeWaitlistQuestion', 'How does the waiting list work?'),
  ('FaqPage', 'placeWaitlistAnswer', 'It is by room and by date you joined, not by who calls most. When a space comes up we work down the list and you get about a week to decide. Nobody moves up for paying more, and there is nothing to pay to be on it.'),
  ('FaqPage', 'placeAheadQuestion', 'How far ahead should we apply?'),
  ('FaqPage', 'placeAheadAnswer', 'For the infant room, as soon as you are ready to tell people you are expecting — that room runs six to nine months behind. Toddler and preschool places move faster, often within a term.'),
  ('FaqPage', 'placeHoldQuestion', 'Can we hold a place for a later start?'),
  ('FaqPage', 'placeHoldAnswer', 'Yes, for up to two months, with the deposit paid. Longer than that and we would be holding an empty room a family on the list needs, so we would rather put you back near the top for the month you actually want.'),
  ('FaqPage', 'placeDaysQuestion', 'Can we choose which days?'),
  ('FaqPage', 'placeDaysAnswer', 'You choose a schedule rather than individual days: five days, Monday–Wednesday–Friday, or Tuesday–Thursday. Fixed days mean your child has the same group around them each time, which is most of what makes them settle.'),
  ('FaqPage', 'startingHeading', 'Starting here'),
  ('FaqPage', 'startingSettleQuestion', 'What does the first week look like?'),
  ('FaqPage', 'startingSettleAnswer', 'Two short visits with you in the room before the start date, then a half day, then a full one. Some children skip straight to the full day and some need a fortnight, and neither is a problem — we follow your child rather than the plan.'),
  ('FaqPage', 'startingBringQuestion', 'What do we need to bring?'),
  ('FaqPage', 'startingBringAnswer', 'A change of clothes, a coat that can get muddy, and whatever your child sleeps with. Not nappies, wipes, sunscreen, or food — those are in the rate, so nobody is scrambling at seven in the morning.'),
  ('FaqPage', 'startingHearQuestion', 'How will we hear about our child''s day?'),
  ('FaqPage', 'startingHearAnswer', 'Under threes get the day written down — every bottle, nap, and nappy — handed to you at pickup. Older children get it told to you at the door by the teacher who was actually with them, which is more use than a form.'),
  ('FaqPage', 'dailyHeading', 'Day to day'),
  ('FaqPage', 'dailyFoodQuestion', 'Who cooks, and what about allergies?'),
  ('FaqPage', 'dailyFoodAnswer', 'Sofia cooks every meal on site, which is why we can be exact about an allergy rather than hopeful about a label. Allergies are posted in the kitchen and in the room, and we do not ask you to send a separate lunch.'),
  ('FaqPage', 'dailyNappiesQuestion', 'How does toilet learning work?'),
  ('FaqPage', 'dailyNappiesAnswer', 'On your child''s timeline and in step with whatever you are doing at home. We will never tell you a child has to be out of nappies to move rooms, and nobody is made to feel behind.'),
  ('FaqPage', 'dailySleepQuestion', 'What if our child does not nap?'),
  ('FaqPage', 'dailySleepAnswer', 'They rest quietly with a book instead. No child is kept on a cot for two hours because the room has a nap time, and no child is woken because pickup is coming.'),
  ('FaqPage', 'dailyOutsideQuestion', 'Do they go outside when it rains?'),
  ('FaqPage', 'dailyOutsideAnswer', 'Yes, most days — this is Portland, and a year indoors waiting for dry weather is not a childhood. Send a coat and boots that you do not mind coming home unrecognisable.'),
  ('FaqPage', 'dailyScreensQuestion', 'Is there screen time?'),
  ('FaqPage', 'dailyScreensAnswer', 'No screens in any room, at any age. Not as a rule we are proud of, just one we have never needed to break.'),
  ('FaqPage', 'troubleHeading', 'When something goes wrong'),
  ('FaqPage', 'troubleSickQuestion', 'When is a child too unwell to come?'),
  ('FaqPage', 'troubleSickAnswer', 'Fever, vomiting, or anything contagious means going home and staying home for twenty-four clear hours after it stops. It is genuinely inconvenient, and it is the reason the whole room is not unwell the following week.'),
  ('FaqPage', 'troubleBitingQuestion', 'What if our child bites, or is bitten?'),
  ('FaqPage', 'troubleBitingAnswer', 'Both sets of parents are told the same day, and neither child is named to the other family. Biting is normal in a toddler room and it is our job to shadow and redirect, not to ask a two-year-old to explain themselves.'),
  ('FaqPage', 'troubleInjuryQuestion', 'What happens if our child is hurt?'),
  ('FaqPage', 'troubleInjuryAnswer', 'Anything above a scraped knee gets a phone call while it is happening, not a note at pickup. Every injury is written up and you sign the record, including the ones that turned out to be nothing.'),
  ('FaqPage', 'troubleComplaintQuestion', 'How do we complain about you?'),
  ('FaqPage', 'troubleComplaintAnswer', 'Tell Maria directly and you will get an answer within two days. If that does not settle it, the state licensing office takes complaints about us without going through us at all, and we will give you the number ourselves.'),
  ('FaqPage', 'visitHeading', 'Ask us the rest in person'),
  ('FaqPage', 'visitBody', 'A list like this answers the questions we have already been asked. Yours may not be here, and the fastest way through it is standing in the building asking a person who can say “I do not know, let me find out” rather than picking from a page.'),
  ('HomePage', 'heroEyebrow', 'Licensed child care · Ages {ageRange}'),
  ('HomePage', 'heroHeading', 'A place where your child is known by name.'),
  ('HomePage', 'heroBody', 'A small, licensed center in {neighborhood}, where the same caregivers greet your child every morning and can tell you exactly how their day went.'),
  ('HomePage', 'planVisit', 'Plan a visit'),
  ('HomePage', 'trustInfantRatio', 'Infant ratio'),
  ('HomePage', 'trustYearsCaring', 'Caring for families'),
  ('HomePage', 'trustOpenWeekdays', 'Open weekdays'),
  ('HomePage', 'trustStateLicense', 'State license'),
  ('HomePage', 'programsHeading', 'Programs by age'),
  ('HomePage', 'infantsBlurb', 'One primary caregiver per child, so feeds, naps, and first words are tracked by someone who knows your baby — not whoever is free.'),
  ('HomePage', 'toddlersBlurb', 'Room to move and language everywhere. Days are predictable so a toddler learning the world can count on what comes next.'),
  ('HomePage', 'preschoolBlurb', 'Early literacy, numbers, and the harder work of taking turns and naming feelings — the groundwork for kindergarten.'),
  ('HomePage', 'dayHeading', 'A day at Willow Grove'),
  ('HomePage', 'dayBody', 'Predictable rhythm, room to be a kid. Here is what nine hours actually looks like.'),
  ('HomePage', 'staffHeading', 'The people who will know your child'),
  ('HomePage', 'testimonialHeading', 'From a parent'),
  ('HomePage', 'testimonialQuote', '“On day three, Aisha told me my daughter only settles for her nap if she can hold the blue elephant. I hadn''t told anyone that. That''s when I stopped worrying.”'),
  ('HomePage', 'testimonialAttribution', 'Priya R., parent of an infant-room child'),
  ('HomePage', 'visitHeading', 'Come see it for yourself'),
  ('HomePage', 'contactAddress', 'Address'),
  ('HomePage', 'contactHours', 'Hours'),
  ('HomePage', 'contactPhone', 'Phone'),
  ('HomePage', 'mapLabel', 'Map of {neighborhood}'),
  ('Footer', 'tagline', 'Licensed child care facility · State license {licenseNumber} · Serving families since {since}.')
) as v (namespace, key, value)
where o.slug = 'willow-grove'
on conflict (org_id, locale, namespace, key) where status = 'published'
do update set value = excluded.value;
